const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DAY=86400000, VERSION="16.2", KEY="sharkHabitsV162";
const SHARKS=[
["grey","Requin gris",0],["blacktip","Requin pointe noire",300],["whitetip","Requin pointe blanche",350],["blue","Requin bleu",420],["nurse","Requin nourrice",500],["lemon","Requin citron",600],["reef","Requin de récif",700],["coral","Requin corail",750],["zebra","Requin zèbre",850],["wobbegong","Wobbegong",950],["angel","Requin ange",1050],["bull","Requin bouledogue",1200],["thresher","Requin-renard",1400],["mako","Requin mako",1600],["hammer","Requin marteau",1800],["great-hammer","Grand requin marteau",2200],["tiger","Requin-tigre",2500],["great-white","Grand requin blanc",3000],["whale","Requin-baleine",3500],["basking","Requin pèlerin",3800],["greenland","Requin du Groenland",4200],["sixgill","Requin griset",4600],["saw","Requin-scie",5000],["frilled","Requin-lézard",5500],["goblin","Requin-lutin",6500],["megalodon","Mégalodon",10000]
].map(([id,name,cost])=>({id,name,cost,img:`shark-${id}.png`}));
const DECOR_FILES=["decor-seaweed.png","decor-kelp.png","decor-coral-red.png","decor-rock.png","decor-shell.png","decor-anemone.png","decor-chest.png","decor-jelly.png","decor-statue.png","decor-wreck.png","decor-clownfish.svg","decor-bluefish.svg","decor-school.svg","decor-turtle.svg","decor-babyturtle.svg"];
const DNAME={"decor-seaweed.png":"Algues","decor-kelp.png":"Kelp","decor-coral-red.png":"Corail rouge","decor-rock.png":"Rocher","decor-shell.png":"Coquillage","decor-anemone.png":"Anémone","decor-chest.png":"Coffre","decor-jelly.png":"Méduse","decor-statue.png":"Statue","decor-wreck.png":"Épave","decor-clownfish.svg":"Poisson-clown","decor-bluefish.svg":"Poisson bleu","decor-school.svg":"Banc de poissons","decor-turtle.svg":"Tortue marine","decor-babyturtle.svg":"Jeune tortue"};
const DECORS=DECOR_FILES.map((img,i)=>({id:img.replace(/\..+$/,'').replace('decor-',''),img,name:DNAME[img]||img,cost:70+i*30}));
const iso=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},today=()=>iso(new Date()),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const monday=d=>{d=new Date(d);let n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(12,0,0,0);return d};
function blank(){let inv={seaweed:1,kelp:1,rock:1};return {version:VERSION,teeth:100,goals:[],entries:[],rewardLog:{},ownedSharks:["grey"],activeShark:"grey",inventory:inv,placed:[{id:uid(),decor:"seaweed",x:8,y:68},{id:uid(),decor:"kelp",x:70,y:58},{id:uid(),decor:"rock",x:42,y:76}],created:today()}}
function migrate(){let d=JSON.parse(localStorage.getItem(KEY)||'null');if(d)return normalize(d);for(const k of ['sharkHabitsV152','sharkHabitsV151','sharkHabitsV15','sharkHabitsV14','sharkHabitsV132','sharkHabitsV131','sharkHabitsV13']){try{let o=JSON.parse(localStorage.getItem(k)||'null');if(!o)continue;let n=blank();n.teeth=+o.teeth||100;n.goals=(o.goals||[]).map(g=>({...g,type:g.type==='period'?'cumulative':g.type==='once'?'deadline':g.type||'habit'}));n.entries=(o.entries||o.activities||[]).map(e=>({id:e.id||uid(),goal:e.goal||e.goalId,value:+e.value||0,date:e.date||today()}));n.ownedSharks=(o.ownedSharks||[]).map(x=>String(x).replace(/^s\d+$/,'')).filter(x=>SHARKS.some(s=>s.id===x));if(!n.ownedSharks.includes('grey'))n.ownedSharks.unshift('grey');n.activeShark=SHARKS.some(s=>s.id===o.activeShark)?o.activeShark:'grey';localStorage.setItem(KEY,JSON.stringify(n));return n}catch(e){}}return blank()}
function normalize(d){d.version=VERSION;d.goals||=[];d.entries||=[];d.rewardLog||={};d.ownedSharks||=['grey'];if(!d.ownedSharks.includes('grey'))d.ownedSharks.unshift('grey');if(!SHARKS.some(s=>s.id===d.activeShark))d.activeShark='grey';d.inventory||={seaweed:1,kelp:1,rock:1};d.placed||=[];return d}
let data=migrate(),selectedDate=today(),reportTab='progress',shopTab='decor',editMode=false;const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function entries(g){return data.entries.filter(e=>e.goal===g.id).sort((a,b)=>a.date.localeCompare(b.date))}
function bounds(g,dateStr=selectedDate){let d=new Date(dateStr+'T12:00'),a,b;if(g.repeat==='day')a=b=d;else if(g.repeat==='week'){a=monday(d);b=new Date(a.getTime()+6*DAY)}else if(g.repeat==='month'){a=new Date(d.getFullYear(),d.getMonth(),1,12);b=new Date(d.getFullYear(),d.getMonth()+1,0,12)}else{a=new Date((g.created||today())+'T12:00');b=g.deadline?new Date(g.deadline+'T12:00'):d}return[iso(a),iso(b)]}
function current(g,dateStr=selectedDate){let es=entries(g);if(g.type==='metric'){let e=es.filter(x=>x.date<=dateStr).at(-1);return e?e.value:(g.startValue??0)}let[a,b]=bounds(g,dateStr);return es.filter(x=>x.date>=a&&x.date<=b).reduce((s,x)=>s+x.value,0)}
function metricDirection(g){if(g.direction&&g.direction!=='auto')return g.direction;if(g.startValue==null)return'increase';return g.target<g.startValue?'decrease':g.target>g.startValue?'increase':'maintain'}
function pct(g,dateStr=selectedDate){let v=current(g,dateStr);if(g.type==='metric'&&g.startValue!=null){let dir=metricDirection(g);if(dir==='maintain'){let tol=Math.max(Math.abs(g.target)*.05,1);return Math.max(0,Math.min(100,100-Math.abs(v-g.target)/tol*100))}let total=Math.abs(g.target-g.startValue)||1,done=dir==='decrease'?g.startValue-v:v-g.startValue;return Math.max(0,Math.min(100,done/total*100))}return Math.max(0,Math.min(100,g.target?100*v/g.target:0))}
function expected(g,dateStr=selectedDate){let[a,b]=bounds(g,dateStr),A=new Date(a+'T12:00'),B=new Date(b+'T12:00');if(g.type==='metric'&&g.deadline){A=new Date((g.created||a)+'T12:00');B=new Date(g.deadline+'T12:00')}let D=new Date(dateStr+'T12:00'),f=Math.max(0,Math.min(1,(D-A)/Math.max(DAY,B-A)));if(g.type==='metric'&&g.startValue!=null){if(metricDirection(g)==='maintain')return g.target;return g.startValue+(g.target-g.startValue)*f}return g.target*f}
function stat(g,dateStr=selectedDate){let v=current(g,dateStr),e=expected(g,dateStr),dir=metricDirection(g),diff=g.type==='metric'?(dir==='decrease'?e-v:dir==='maintain'?-Math.abs(v-e):v-e):v-e;return{v,e,diff,good:diff>=0}}
function theoreticalSeries(g,points=13){let[a,b]=bounds(g,selectedDate),A=new Date(a+'T12:00'),B=new Date(b+'T12:00');if(g.type==='metric'&&g.deadline){A=new Date((g.created||a)+'T12:00');B=new Date(g.deadline+'T12:00')}let span=Math.max(DAY,B-A);return Array.from({length:points},(_,i)=>{let d=new Date(A.getTime()+span*i/(points-1));return{date:iso(d),value:expected(g,iso(d))}})}
function actualSeries(g){let es=entries(g);if(g.type==='metric')return es.map(e=>({date:e.date,value:e.value}));let[a,b]=bounds(g,selectedDate),sum=0;return es.filter(e=>e.date>=a&&e.date<=b).map(e=>({date:e.date,value:(sum+=e.value)}))}
function typeMeta(g){return g.type==='habit'?{icon:'✓',label:'HABITUDE',cls:'habit'}:g.type==='cumulative'?{icon:'↗',label:'CUMUL',cls:'cumulative'}:g.type==='metric'?{icon:'∿',label:'MESURE',cls:'metric'}:{icon:'◎',label:'ÉCHÉANCE',cls:'deadline'}}
function periodLabel(g){return g.repeat==='day'?'aujourd’hui':g.repeat==='week'?'cette semaine':g.repeat==='month'?'ce mois':'au total'}
const fmt=n=>Number.isInteger(+n)?String(+n):(+n).toFixed(1).replace('.',',');
function isDone(g,dateStr=selectedDate){if(g.type==='metric'){let s=stat(g,dateStr);return s.good}return current(g,dateStr)>=g.target}
function scheduledOn(g,dateStr){let d=new Date(dateStr+'T12:00'),mode=g.scheduleMode||'period';if(mode==='days')return(g.scheduleDays||[]).map(Number).includes(d.getDay());return true}
function strideStatus(g,dateStr=selectedDate){let v=current(g,dateStr),e=expected(g,dateStr),rule=g.rule||'atleast',good;if(g.type==='metric'){let dir=metricDirection(g);good=dir==='decrease'?v<=e:dir==='maintain'?Math.abs(v-e)<=Math.max(Math.abs(g.target)*.02,.2):v>=e}else if(rule==='atmost')good=v<=g.target;else if(rule==='about')good=Math.abs(v-e)<=Math.max(Math.abs(g.target)*.1,1);else good=v>=e;return{v,e,good,diff:v-e}}
function prevPeriodDate(period){let d=new Date(selectedDate+'T12:00');if(period==='week')d.setDate(d.getDate()-7);else if(period==='month')d.setMonth(d.getMonth()-1);else if(period==='year')d.setFullYear(d.getFullYear()-1);else d.setDate(d.getDate()-30);return iso(d)}
function renderWeek(){let s=monday(new Date(selectedDate+'T12:00'));$('#week').innerHTML=Array.from({length:7},(_,i)=>new Date(s.getTime()+i*DAY)).map(d=>{let id=iso(d),done=data.goals.some(g=>data.entries.some(e=>e.goal===g.id&&e.date===id));return `<button class="day ${id===selectedDate?'active':''} ${done?'done':''}" data-date="${id}"><span>${d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','').toUpperCase()}</span><b>${d.getDate()}</b></button>`}).join('')}
function task(g,kind){let s=strideStatus(g),p=pct(g),m=typeMeta(g),v=s.v,identity='';if(g.type==='habit'){let st=monday(new Date(selectedDate+'T12:00'));identity=`<div class="habitWeek">${Array.from({length:7},(_,i)=>iso(new Date(st.getTime()+i*DAY))).map(d=>`<i class="${entries(g).some(e=>e.date===d&&e.value>0)?'hit':''}">${entries(g).some(e=>e.date===d&&e.value>0)?'✓':'·'}</i>`).join('')}</div>`}else if(g.type==='cumulative'){identity=`<div class="identityBar"><i style="width:${p}%"></i></div><small>${fmt(v)} / ${fmt(g.target)} ${g.unit||''} ${periodLabel(g)}</small>`}else if(g.type==='metric'){identity=`<div class="trajectoryToday"><span>Théorique aujourd’hui <b>${fmt(s.e)} ${g.unit||''}</b></span><strong class="${s.good?'good':'bad'}">${s.good?'✓ Dans le rythme':'À surveiller'} · écart ${fmt(Math.abs(v-s.e))} ${g.unit||''}</strong></div>`}else{identity=`<div class="identityBar"><i style="width:${p}%"></i></div><small>${Math.round(p)} % · ${g.deadline||'sans échéance'}</small>`}return`<article class="trackingCard ${m.cls} ${kind==='missed'?'missed':''}" data-detail="${g.id}"><div class="trackHead"><div><span class="typeTag">${m.icon} ${m.label}</span><h4>${g.name}</h4></div><strong class="trackValue">${fmt(v)}${g.unit?` ${g.unit}`:''}</strong></div><div class="identity">${identity}</div><div class="trackFoot"><span class="${s.good?'good':'bad'}">${s.good?'Dans le rythme':'À surveiller'}</span><div class="stepper"><button data-minus="${g.id}">−</button><button data-add="${g.id}">＋</button></div></div></article>`}
function renderToday(){renderWeek();let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,selectedDate)),todo=[],done=[],miss=[];gs.forEach(g=>{let has=data.entries.some(e=>e.goal===g.id&&e.date===selectedDate),complete=g.type==='metric'?has:(g.type==='habit'?dailyAmount(g,selectedDate)>=1:isDone(g));if(complete)done.push(g);else if(selectedDate<today())miss.push(g);else todo.push(g)});$('#todayGroups').innerHTML=[['À faire',todo,'todo'],['Terminé',done,'done'],['Manqué',miss,'missed']].filter(x=>x[1].length).map(x=>`<div class="groupTitle"><h3>${x[0]}</h3><span>${x[1].length}</span></div><div class="taskGroup">${x[1].map(g=>task(g,x[2])).join('')}</div>`).join('')||`<div class="emptyState"><div class="emptyIcon">✓</div><strong>Rien de prévu</strong><p class="muted">Aucun objectif n’est planifié ce jour.</p></div>`;let avg=gs.length?gs.reduce((s,g)=>s+pct(g),0)/gs.length:0;$('#dayScore').textContent=Math.round(avg)+' %';$('#dayBar').style.width=avg+'%'}
function reportRow(g){let s=stat(g),p=pct(g);return `<button class="goalRow" data-detail="${g.id}" style="width:100%;text-align:left;color:inherit"><div class="row"><div><h3>${g.name}</h3><div class="pace">${g.category||'Autre'}</div></div><div class="big">${fmt(s.v)}${g.unit?` ${g.unit}`:''}</div></div><div class="miniBar"><i style="width:${p}%;background:${s.good?'var(--green)':'var(--red)'}"></i></div><div class="row pace"><span>${Math.round(p)} %</span><span class="${s.good?'good':'bad'}">${s.good?'En bonne voie':'En retard'} · attendu ${fmt(s.e)}${g.unit?` ${g.unit}`:''}</span></div></button>`}
let reportPeriod='week';
function renderReports(){let all=data.goals.filter(g=>!g.archived),filtered=all.filter(g=>reportTab==='all'||(reportTab==='good'?strideStatus(g).good:!strideStatus(g).good)),avg=all.length?all.reduce((s,g)=>s+pct(g),0)/all.length:0,good=all.filter(g=>strideStatus(g).good).length,prev=prevPeriodDate(reportPeriod),prevAvg=all.length?all.reduce((s,g)=>s+pct(g,prev),0)/all.length:0,trend=Math.round(avg-prevAvg);$('#reportSummary').innerHTML=`<div class="reportHero premiumHero"><span class="eyebrow">STATUT GLOBAL · ${reportPeriod==='week'?'SEMAINE':reportPeriod==='month'?'MOIS':reportPeriod==='year'?'ANNÉE':'TOUT'}</span><div class="heroScore">${Math.round(avg)}<small>%</small></div><div class="heroMeta"><span>${good} dans le rythme</span><span>${all.length-good} à surveiller</span><span class="${trend>=0?'good':'bad'}">${trend>=0?'↗':'↘'} ${Math.abs(trend)} pts</span></div><div class="bar"><i style="width:${avg}%"></i></div></div>`;$('#reportList').innerHTML=filtered.map(reportRow).join('')||'<div class="emptyState"><strong>Aucun objectif ici</strong></div>'}
function renderOcean(){$('#teeth').textContent=data.teeth;scene($('#aquariumPreview'))}
function sharkCard(s,shop=false){let own=data.ownedSharks.includes(s.id),active=data.activeShark===s.id;return `<div class="card"><div class="assetBox"><img src="${s.img}" alt="${s.name}"></div><h3>${s.name}</h3><div class="muted">${own?(active?'Actif':'Débloqué'):`${s.cost} 🦷`}</div><button data-shark="${s.id}" data-mode="${shop?'buy':'select'}">${shop?(own?'Possédé':'Acheter'):(own?(active?'Actif':'Choisir'):'🔒 Voir')}</button></div>`}
function renderSharks(){$('#ownedCount').textContent=`${data.ownedSharks.length} / ${SHARKS.length}`;$('#sharkGrid').innerHTML=SHARKS.map(s=>sharkCard(s)).join('')}
function decorCard(d){let qty=data.inventory[d.id]||0;return `<div class="card"><div class="assetBox"><img src="${d.img}" alt="${d.name}"></div><h3>${d.name}</h3><div class="muted">${qty?`${qty} disponible${qty>1?'s':''}`:`${d.cost} 🦷`}</div><button data-decor="${d.id}">${qty?'Placer':'Acheter'}</button></div>`}
function renderShop(){if(shopTab==='collection'){let owned=SHARKS.filter(s=>data.ownedSharks.includes(s.id));$('#shopGrid').innerHTML=`<div class="collectionSummary"><strong>${owned.length} / ${SHARKS.length} requins</strong><span>Collection</span></div>`+owned.map(s=>`<button class="shopItem" data-shark="${s.id}"><img src="${s.img}" alt=""><b>${s.name}</b><small>Possédé · choisir</small></button>`).join('');return}$('#shopTeeth').textContent=data.teeth;$('#shopGrid').innerHTML=shopTab==='decor'?DECORS.map(decorCard).join(''):SHARKS.map(s=>sharkCard(s,true)).join('')}
function renderInv(){$('#inventory').classList.toggle('visible',editMode);$('#inventory').innerHTML=DECORS.filter(d=>(data.inventory[d.id]||0)>0).map(d=>`<button data-place="${d.id}"><img src="${d.img}"><span>${d.name} ×${data.inventory[d.id]}</span></button>`).join('')||'<span class="muted">Aucune décoration disponible.</span>'}
function render(){renderToday();renderReports();renderOcean();renderSharks();renderShop();if($('#aquariumDialog').open){scene($('#aquariumFull'));renderInv()}}
function reward(g,date){if(g.type==='metric'||date>today())return;let[a,b]=bounds(g,date),period=g.repeat==='day'?date:g.repeat==='week'?a:g.repeat==='month'?a:(g.deadline||a),k=`${g.id}:${period}`;if(!isDone(g,date)||data.rewardLog[k])return;data.rewardLog[k]=true;data.teeth+=3}
function openEntry(g){let f=$('#entryForm');f.reset();f.goal.value=g.id;f.date.value=selectedDate;f.value.value=g.type==='habit'?1:'';$('#entryTitle').textContent=g.type==='metric'?'Nouvelle mesure':g.type==='habit'?'Ajouter une occurrence':'Ajouter au cumul';$('#entryDialog').showModal()}
function openGoal(g=null){let f=$('#goalForm');f.reset();f.dataset.editingId=g?.id||'';if(f.elements.id)f.elements.id.value=g?.id||'';$('#goalDialogTitle').textContent=g?'Modifier':'Nouveau suivi';if(g){Object.keys(g).forEach(k=>{if(k!=='scheduleDays'&&f.elements[k])f.elements[k].value=g[k]??''});$('#goalForm input[name=day]').forEach(x=>x.checked=(g.scheduleDays||[]).map(Number).includes(+x.value))}$('#goalDialog').showModal()}
function detail(g){let s=stat(g),es=entries(g),ideal=theoreticalSeries(g),real=actualSeries(g),m=typeMeta(g),all=[...ideal.map(x=>x.value),...real.map(x=>x.value),g.target].filter(Number.isFinite),mn0=Math.min(...all),mx0=Math.max(...all),pad=(mx0-mn0||1)*.12,mn=mn0-pad,mx=mx0+pad,rg=mx-mn||1,dates=[...ideal.map(x=>x.date),...real.map(x=>x.date)].sort(),first=dates[0]||today(),last=dates.at(-1)||today(),t0=new Date(first+'T12:00').getTime(),span=Math.max(DAY,new Date(last+'T12:00').getTime()-t0),pts=arr=>arr.map(x=>`${5+(new Date(x.date+'T12:00').getTime()-t0)/span*90},${92-(x.value-mn)/rg*82}`).join(' ');$('#detailTitle').textContent=g.name;$('#detailBody').dataset.goal=g.id;$('#detailBody').innerHTML=`<div class="detailCard"><span class="typeTag">${m.icon} ${m.label}</span><div class="metric3"><div><span class="muted">Objectif</span><strong>${fmt(g.target)}</strong></div><div><span class="muted">Actuel</span><strong>${fmt(s.v)}</strong></div><div><span class="muted">Théorique</span><strong>${fmt(s.e)}</strong></div></div><div class="legend"><span>━ Réel</span><span>┄ Trajectoire théorique</span></div><div class="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts(ideal)}" fill="none" stroke="#0a84ff" stroke-width="1.5" stroke-dasharray="3 2"/><polyline points="${pts(real)}" fill="none" stroke="#34c759" stroke-width="2.5"/></svg></div><p class="${s.good?'good':'bad'}">${s.good?'Dans le rythme / en avance':'Derrière la trajectoire'} · écart ${fmt(Math.abs(s.diff))} ${g.unit||''}</p></div><div class="history"><div class="historyHead"><h3>Historique</h3><button data-add="${g.id}">＋ Ajouter</button></div>${es.slice().reverse().map(e=>`<div class="row"><span>${new Date(e.date+'T12:00').toLocaleDateString('fr-FR')}</span><span><strong>${fmt(e.value)} ${g.unit||''}</strong> <button class="historyDelete" data-delete-entry="${e.id}">Supprimer</button></span></div>`).join('')||'<p class="muted">Aucune donnée.</p>'}</div>`;$('#editGoal').onclick=()=>{$('#detailDialog').close();openGoal(g)};$('#detailDialog').showModal()}
function subtract(g){let day=entries(g).filter(e=>e.date===selectedDate);if(!day.length)return alert('Aucune saisie à retirer ce jour.');if(g.type==='metric'){let last=day.at(-1);data.entries=data.entries.filter(e=>e.id!==last.id)}else{let raw=prompt(`Combien retirer (${g.unit||'unité'}) ?`,g.type==='habit'?'1':'');if(raw===null)return;let n=+String(raw).replace(',','.');if(!(n>0))return;let remaining=n;for(let i=data.entries.length-1;i>=0&&remaining>0;i--){let e=data.entries[i];if(e.goal!==g.id||e.date!==selectedDate||e.value<=0)continue;let take=Math.min(e.value,remaining);e.value-=take;remaining-=take;if(e.value<=0)data.entries.splice(i,1)}}save();render()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));$('#title').textContent={today:'Aujourd’hui',reports:'Rapports',ocean:'Mon océan',sharks:'Boutique',shop:'Boutique'}[b.dataset.page];scrollTo(0,0);return}if(b.dataset.date){selectedDate=b.dataset.date;renderToday();return}if(b.dataset.add){openEntry(data.goals.find(g=>g.id===b.dataset.add));e.stopPropagation();return}if(b.dataset.minus){subtract(data.goals.find(g=>g.id===b.dataset.minus));e.stopPropagation();return}if(b.dataset.detail){let g=data.goals.find(x=>x.id===b.dataset.detail);if(g)detail(g);return}if(b.dataset.close!==undefined){b.closest('dialog').close();return}if(b.dataset.period){reportPeriod=b.dataset.period;$$('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderReports();return}if(b.dataset.report){reportTab=b.dataset.report;$$('[data-report]').forEach(x=>x.classList.toggle('active',x===b));renderReports();return}if(b.dataset.shop){shopTab=b.dataset.shop;$$('[data-shop]').forEach(x=>x.classList.toggle('active',x===b));renderShop();return}if(b.dataset.shark){let s=SHARKS.find(x=>x.id===b.dataset.shark),own=data.ownedSharks.includes(s.id);if(b.dataset.mode==='buy'&&!own){if(data.teeth<s.cost)return alert('Pas assez de dents.');data.teeth-=s.cost;data.ownedSharks.push(s.id)}else if(own)data.activeShark=s.id;else return alert(`Disponible dans la boutique pour ${s.cost} dents.`);save();render();return}if(b.dataset.decor){let d=DECORS.find(x=>x.id===b.dataset.decor);if((data.inventory[d.id]||0)>0){data.inventory[d.id]--;data.placed.push({id:uid(),decor:d.id,x:10+Math.random()*65,y:55+Math.random()*25})}else{if(data.teeth<d.cost)return alert('Pas assez de dents.');data.teeth-=d.cost;data.inventory[d.id]=(data.inventory[d.id]||0)+1}save();render();return}if(b.dataset.place){if((data.inventory[b.dataset.place]||0)<1)return;data.inventory[b.dataset.place]--;data.placed.push({id:uid(),decor:b.dataset.place,x:10+Math.random()*65,y:55+Math.random()*25});save();render();return}if(b.dataset.remove&&editMode){let p=data.placed.find(x=>x.id===b.dataset.remove);if(p){data.inventory[p.decor]=(data.inventory[p.decor]||0)+1;data.placed=data.placed.filter(x=>x.id!==p.id);save();render()}return}if(b.dataset.deleteEntry){data.entries=data.entries.filter(x=>x.id!==b.dataset.deleteEntry);save();let g=data.goals.find(x=>x.id===b.closest('#detailBody')?.dataset.goal);render();$('#detailDialog').close();return}});
$('#newGoal').onclick=()=>openGoal();$('#goalForm').onsubmit=e=>{e.preventDefault();let f=e.currentTarget,o=Object.fromEntries(new FormData(f));o.target=+o.target;o.startValue=o.startValue===''?null:+o.startValue;o.timesPerWeek=+o.timesPerWeek||3;o.scheduleDays=$$('#goalForm input[name=day]:checked').map(x=>+x.value);o.created=o.created||today();o.archived=false;o.direction=o.direction||'auto';o.rule=o.rule||'atleast';o.scheduleMode=o.scheduleMode||'period';let editingId=f.dataset.editingId||'',i=editingId?data.goals.findIndex(g=>String(g.id)===String(editingId)):-1;if(i>=0){o.id=data.goals[i].id;data.goals[i]={...data.goals[i],...o}}else{o.id=uid();while(data.goals.some(g=>String(g.id)===String(o.id)))o.id=uid();data.goals.push(o)}f.dataset.editingId='';save();$('#goalDialog').close();render()};
$('#entryForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.currentTarget)),g=data.goals.find(x=>x.id===o.goal),v=+o.value;if(!g||!Number.isFinite(v)||v<0)return;if(g.type==='metric')data.entries=data.entries.filter(x=>!(x.goal===g.id&&x.date===o.date));data.entries.push({id:uid(),goal:g.id,value:v,date:o.date});reward(g,o.date);save();$('#entryDialog').close();render()};
$('#oceanCard').onclick=()=>{editMode=false;scene($('#aquariumFull'));renderInv();$('#aquariumDialog').showModal()};$('#decorate').onclick=()=>$('#oceanCard').click();$('#manageSharks').onclick=()=>{shopTab='sharks';$('[data-page=shop]').click();renderShop()};$('#editAquarium').onclick=()=>{editMode=!editMode;$('#editAquarium').textContent=editMode?'OK':'Décorer';scene($('#aquariumFull'));renderInv()};$('#settingsBtn').onclick=()=>alert('SharkHabits V16.1 — Tracking Identity\nRequin gris de départ · données stockées localement.');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
