/* SharkHabits V16.10 — goal lifecycle */
const V1610='16.10';
function activeGoal(g){return !g.archivedAt&&!g.completedAt}
function archiveGoal(g){g.archivedAt=today();save();document.querySelector('#detailDialog')?.close();render();showActionToast('Objectif archivé')}
function restoreGoal(g){delete g.archivedAt;delete g.completedAt;save();render();showActionToast('Objectif restauré')}
function completeGoal(g){g.completedAt=today();delete g.archivedAt;save();document.querySelector('#detailDialog')?.close();render();showActionToast('Objectif terminé')}
function deleteGoalForever(g){if(!confirm(`Supprimer définitivement « ${g.name} » et tout son historique ?`))return;data.goals=data.goals.filter(x=>x.id!==g.id);data.entries=data.entries.filter(e=>e.goal!==g.id);Object.keys(data.rewardLog||{}).filter(k=>k.startsWith(g.id+':')).forEach(k=>delete data.rewardLog[k]);save();document.querySelector('#detailDialog')?.close();render();showActionToast('Objectif supprimé')}
const v1610RenderToday=renderToday;renderToday=function(){let hidden=data.goals.filter(g=>!activeGoal(g));data.goals=data.goals.filter(activeGoal);try{v1610RenderToday()}finally{data.goals=[...data.goals,...hidden]}}
const v1610RenderReports=renderReports;renderReports=function(){v1610RenderReports();let host=$('#reportList');if(!host)return;let inactive=data.goals.filter(g=>g.archivedAt||g.completedAt);if(!inactive.length)return;let sec=document.createElement('section');sec.className='inactiveGoals';sec.innerHTML=`<div class="sectionHead"><div><span class="eyebrow">HISTORIQUE</span><h2>Terminés & archivés</h2></div><span>${inactive.length}</span></div><div class="inactiveGoalList">${inactive.map(g=>`<button class="inactiveGoal" data-inactive="${g.id}"><span><strong>${esc(g.name)}</strong><small>${g.completedAt?'Terminé':'Archivé'} · ${g.completedAt||g.archivedAt}</small></span><span>›</span></button>`).join('')}</div>`;host.appendChild(sec);sec.querySelectorAll('[data-inactive]').forEach(b=>b.onclick=()=>detail(data.goals.find(g=>g.id===b.dataset.inactive)))}
const v1610Detail=detail;detail=function(g){v1610Detail(g);let body=$('#detailBody');if(!body)return;body.querySelector('.goalLifecycle')?.remove();let box=document.createElement('div');box.className='goalLifecycle';if(g.archivedAt||g.completedAt){box.innerHTML=`<button class="lifecycleRestore">Restaurer l’objectif</button><button class="lifecycleDelete danger">Supprimer définitivement</button>`;box.querySelector('.lifecycleRestore').onclick=()=>restoreGoal(g)}else{box.innerHTML=`<button class="lifecycleComplete">✓ Terminer</button><button class="lifecycleArchive">Archiver</button><button class="lifecycleDelete danger">Supprimer définitivement</button>`;box.querySelector('.lifecycleComplete').onclick=()=>completeGoal(g);box.querySelector('.lifecycleArchive').onclick=()=>archiveGoal(g)}box.querySelector('.lifecycleDelete').onclick=()=>deleteGoalForever(g);body.appendChild(box)}
if(typeof data!=='undefined'){data.version=V1610;save();render()}
