/* SharkHabits V16.3.1 QA compatibility layer over V16.2 */
const V1631='16.3.1';
function dailyAmount(g,dateStr=selectedDate){return entries(g).filter(e=>e.date===dateStr).reduce((s,e)=>s+(+e.value||0),0)}
function weekDates(dateStr=selectedDate){let s=monday(new Date(dateStr+'T12:00'));return Array.from({length:7},(_,i)=>iso(new Date(s.getTime()+i*DAY)))}
function targetState(g,dateStr=selectedDate){let v=current(g,dateStr),e=expected(g,dateStr),r=g.rule||'atleast',dir=metricDirection(g),good=false,complete=false;if(g.type==='metric'){if(dir==='decrease'){good=v<=e;complete=v<=g.target}else if(dir==='increase'){good=v>=e;complete=v>=g.target}else{let t=Math.max(Math.abs(g.target)*.05,.2);good=Math.abs(v-g.target)<=t;complete=good}}else if(r==='atmost'){good=v<=g.target;complete=good}else if(r==='about'){let t=Math.max(Math.abs(g.target)*.1,1);good=Math.abs(v-e)<=t;complete=good}else{good=v>=e;complete=v>=g.target}let minOK=g.minimum!==null&&g.minimum!==undefined&&g.minimum!==''&&v>=+g.minimum;return{v,e,good,complete,minOK,diff:v-e,rule:r,dir}}
strideStatus=(g,dateStr=selectedDate)=>targetState(g,dateStr);
function dayState(dateStr){let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,dateStr));if(!gs.length)return'empty';let ok=gs.filter(g=>{let s=targetState(g,dateStr);return g.type==='habit'?dailyAmount(g,dateStr)>0:(s.good||s.complete||s.minOK)}).length;if(ok===gs.length)return'done';if(ok>0)return'partial';return dateStr<today()?'missed':'pending'}
renderWeek=function(){let s=monday(new Date(selectedDate+'T12:00')),e=new Date(s.getTime()+6*DAY),wr=$('#weekRange'),jd=$('#jumpDate');if(wr)wr.textContent=`${s.toLocaleDateString('fr-FR',{day:'numeric',month:'long'})} – ${e.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}`;if(jd)jd.value=selectedDate;$('#week').innerHTML=Array.from({length:7},(_,i)=>new Date(s.getTime()+i*DAY)).map(d=>{let id=iso(d),state=dayState(id);return `<button class="day ${id===selectedDate?'active':''} ${state}" data-date="${id}"><span>${d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','').toUpperCase()}</span><b>${d.getDate()}</b><i></i></button>`}).join('')};
function metricDeltaText(g,dateStr=selectedDate){let s=targetState(g,dateStr),d=Math.abs(s.v-s.e),u=g.unit||'';if(d<.00001)return'Exactement sur la trajectoire';if(s.dir==='decrease')return s.v<s.e?`${fmt(d)} ${u} sous la trajectoire`:`${fmt(d)} ${u} au-dessus de la trajectoire`;return s.v>s.e?`${fmt(d)} ${u} au-dessus de la trajectoire`:`${fmt(d)} ${u} sous la trajectoire`}
function streak(g){let es=entries(g).filter(e=>e.value>0),set=new Set(es.map(e=>e.date)),n=0,d=new Date(Math.min(new Date(selectedDate+'T12:00'),new Date(today()+'T12:00')));while(set.has(iso(d))){n++;d=new Date(d.getTime()-DAY)}return n}
function scene(el){if(!el)return;let shark=SHARKS.find(s=>s.id===data.activeShark)||SHARKS[0];el.innerHTML=`<div class="waterGlow"></div><img class="mainShark" src="${shark.img}" alt="${shark.name}">`+(data.placed||[]).map(p=>{let d=DECORS.find(x=>x.id===p.decor);return d?`<button class="placedDecor" data-remove="${p.id}" style="left:${p.x}%;top:${p.y}%"><img src="${d.img}" alt="${d.name}"></button>`:''}).join('')}
renderShop=function(){if(shopTab==='collection'){$('#shopTeeth').textContent=data.teeth;$('#shopGrid').innerHTML=`<div class="collectionSummary"><strong>${data.ownedSharks.length} / ${SHARKS.length} requins</strong><span>Collection</span></div>`+SHARKS.map(s=>{let own=data.ownedSharks.includes(s.id),active=data.activeShark===s.id;return `<button class="shopItem ${own?'owned':'locked'}" data-shark="${s.id}"><div class="assetBox"><img src="${s.img}" alt="${s.name}"></div><b>${s.name}</b><small>${own?(active?'Actif':'Possédé · choisir'):`🔒 ${s.cost} 🦷`}</small></button>`}).join('');return}$('#shopTeeth').textContent=data.teeth;$('#shopGrid').innerHTML=shopTab==='decor'?DECORS.map(decorCard).join(''):SHARKS.map(s=>sharkCard(s,true)).join('')};
detail=function(g){let s=targetState(g),es=entries(g),ideal=theoreticalSeries(g),real=actualSeries(g),m=typeMeta(g),all=[...ideal.map(x=>x.value),...real.map(x=>x.value),g.target].filter(Number.isFinite),mn0=Math.min(...all),mx0=Math.max(...all),pad=(mx0-mn0||1)*.12,mn=mn0-pad,mx=mx0+pad,rg=mx-mn||1,dates=[...ideal.map(x=>x.date),...real.map(x=>x.date)].sort(),first=dates[0]||today(),last=dates.at(-1)||today(),t0=new Date(first+'T12:00').getTime(),span=Math.max(DAY,new Date(last+'T12:00').getTime()-t0),pts=arr=>arr.map(x=>`${5+(new Date(x.date+'T12:00').getTime()-t0)/span*90},${92-(x.value-mn)/rg*82}`).join(' '),d0=new Date(selectedDate+'T12:00'),y=d0.getFullYear(),mo=d0.getMonth(),fd=new Date(y,mo,1,12),ld=new Date(y,mo+1,0,12),lead=(fd.getDay()+6)%7,cells=Array.from({length:lead},()=>'<i></i>');for(let n=1;n<=ld.getDate();n++){let ds=iso(new Date(y,mo,n,12)),state=dayState(ds);cells.push(`<button class="${state} ${ds===selectedDate?'selected':''}" data-date="${ds}">${n}</button>`)}let status=g.type==='metric'?metricDeltaText(g):(s.complete?'Objectif atteint':s.minOK?'Minimum atteint':s.good?'Dans le rythme':'À surveiller');$('#detailTitle').textContent=g.name;$('#detailBody').dataset.goal=g.id;$('#detailBody').innerHTML=`<div class="detailCard"><span class="typeTag">${m.icon} ${m.label}</span><div class="metric3"><div><span class="muted">Objectif</span><strong>${fmt(g.target)}</strong></div><div><span class="muted">Actuel</span><strong>${fmt(s.v)}</strong></div><div><span class="muted">Théorique</span><strong>${fmt(s.e)}</strong></div></div><div class="legend"><span>━ Réel</span><span>┄ Trajectoire théorique</span></div><div class="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts(ideal)}" fill="none" stroke="#0a84ff" stroke-width="1.5" stroke-dasharray="3 2"/><polyline points="${pts(real)}" fill="none" stroke="#34c759" stroke-width="2.5"/></svg></div><p class="${s.good||s.complete||s.minOK?'good':'bad'}">${status}</p></div><div class="calendarCard"><div class="historyHead"><h3>${d0.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h3><span>🔥 ${streak(g)}</span></div><div class="calHead">${['L','M','M','J','V','S','D'].map(x=>`<b>${x}</b>`).join('')}</div><div class="goalCalendar">${cells.join('')}</div></div><div class="history"><div class="historyHead"><h3>Historique</h3><button data-add="${g.id}">＋ Ajouter</button></div>${es.slice().reverse().map(e=>`<div class="row historyEntry"><span>${new Date(e.date+'T12:00').toLocaleDateString('fr-FR')}${e.note?`<small>${e.note}</small>`:''}</span><span><strong>${fmt(e.value)} ${g.unit||''}</strong> <button class="historyDelete" data-delete-entry="${e.id}">Supprimer</button></span></div>`).join('')||'<p class="muted">Aucune donnée.</p>'}</div>`;$('#editGoal').onclick=()=>{$('#detailDialog').close();openGoal(g)};$('#detailDialog').showModal()};
subtract=function(g){let day=entries(g).filter(e=>e.date===selectedDate);if(!day.length)return;let last=day.at(-1);if(g.type==='metric'||g.type==='habit'||last.value<=1)data.entries=data.entries.filter(e=>e.id!==last.id);else last.value=Math.max(0,last.value-1);save();render()};
const originalEntrySubmit=$('#entryForm').onsubmit;$('#entryForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.currentTarget)),g=data.goals.find(x=>x.id===o.goal),v=+o.value;if(!g||!Number.isFinite(v)||v<0)return;if(g.type==='metric')data.entries=data.entries.filter(x=>!(x.goal===g.id&&x.date===o.date));data.entries.push({id:uid(),goal:g.id,value:v,date:o.date,note:o.entryNote||''});reward(g,o.date);save();$('#entryDialog').close();render()};
const prev=$('#prevWeek'),next=$('#nextWeek'),tb=$('#todayBtn'),jump=$('#jumpDate');if(prev)prev.onclick=()=>{let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()-7);selectedDate=iso(d);render()};if(next)next.onclick=()=>{let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()+7);selectedDate=iso(d);render()};if(tb)tb.onclick=()=>{selectedDate=today();render()};if(jump)jump.onchange=e=>{if(e.target.value){selectedDate=e.target.value;render()}};
document.addEventListener('click',e=>{let b=e.target.closest('button[data-date]');if(!b)return;selectedDate=b.dataset.date;if(b.closest('#detailDialog'))$('#detailDialog').close();render();e.preventDefault();e.stopImmediatePropagation()},true);
const settings=$('#settingsBtn');if(settings)settings.onclick=()=>alert('SharkHabits V16.3.1 — QA\nRequin gris de départ · 26 espèces · données stockées localement.');
data.version=V1631;save();render();
