/* SharkHabits V16.4 UX layer */
const V164='16.4';
function weeklyHits(g,dateStr=selectedDate){let s=monday(new Date(dateStr+'T12:00'));return Array.from({length:7},(_,i)=>{let d=iso(new Date(s.getTime()+i*DAY));return entries(g).some(e=>e.date===d&&+e.value>0)})}
function v164Identity(g,s,p){let v=s.v;if(g.type==='habit'){let hits=weeklyHits(g),target=g.scheduleMode==='timesweek'?Math.max(1,+g.timesPerWeek||1):null;return `<div class="habitDots">${hits.map(x=>`<i class="${x?'hit':''}">${x?'✓':'·'}</i>`).join('')}</div><small>${target?`${hits.filter(Boolean).length} / ${target} cette semaine`:`Série · ${streak(g)} jour${streak(g)>1?'s':''}`}</small>`}if(g.type==='cumulative')return `<div class="identityBar"><i style="width:${p}%"></i></div><small>${fmt(v)} / ${fmt(g.target)} ${g.unit||''} · ${periodLabel(g)}</small>`;if(g.type==='metric')return `<div class="trajectoryToday"><span>${g.deadline?'Trajectoire aujourd’hui':'Cible'} <b>${fmt(g.deadline?s.e:g.target)} ${g.unit||''}</b></span><strong class="${s.good?'good':'bad'}">${metricDeltaText(g)}</strong></div>`;let left=g.deadline?Math.max(0,Math.ceil((new Date(g.deadline+'T12:00')-new Date(selectedDate+'T12:00'))/DAY)):null;return `<div class="identityBar"><i style="width:${p}%"></i></div><small>${Math.round(p)} %${left!==null?` · ${left} jour${left>1?'s':''} restant${left>1?'s':''}`:''}</small>`}
task=function(g,kind){let s=targetState(g),p=pct(g),m=typeMeta(g),v=s.v;return `<article class="trackingCard ${m.cls} ${kind==='missed'?'missed':''}" data-detail="${g.id}"><div class="trackHead"><div><span class="typeTag">${m.icon} ${m.label}</span><h4>${g.name}</h4></div><strong class="trackValue">${fmt(v)}${g.unit?` ${g.unit}`:''}</strong></div><div class="identity">${v164Identity(g,s,p)}</div><div class="trackFoot"><span class="${s.good?'good':'bad'}">${s.good?'Dans le rythme':'À surveiller'}</span><div class="stepper"><button data-minus="${g.id}" aria-label="Soustraire">−</button><button data-add="${g.id}" aria-label="Ajouter">＋</button></div></div></article>`}
const oldRenderToday=renderToday;renderToday=function(){oldRenderToday();let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,selectedDate)),done=gs.filter(g=>g.type==='metric'?data.entries.some(e=>e.goal===g.id&&e.date===selectedDate):(g.type==='habit'?dailyAmount(g,selectedDate)>=1:isDone(g))).length,summary=$('.summary');if(summary){let label=summary.querySelector('span');if(label)label.textContent=`${done}/${gs.length} accomplis · ${selectedDate===today()?'aujourd’hui':new Date(selectedDate+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}`}}
const oldScene=scene;scene=function(el){oldScene(el);if(!el)return;let shark=SHARKS.find(s=>s.id===data.activeShark)||SHARKS[0];el.dataset.shark=shark.id;el.querySelectorAll('.mainShark').forEach(img=>{img.loading='eager';img.decoding='async'})}
const oldOcean=renderOcean;renderOcean=function(){oldOcean();let card=$('#oceanCard');if(card&&!card.parentElement.querySelector('.oceanStatus')){let shark=SHARKS.find(s=>s.id===data.activeShark)||SHARKS[0],x=document.createElement('div');x.className='oceanStatus';x.innerHTML=`<div><strong>${shark.name}</strong><br><small>Requin actif</small></div><strong>🦷 ${data.teeth}</strong>`;card.after(x)}}
function showRewardToast(n=3){let t=$('#rewardToast');if(!t){t=document.createElement('div');t.id='rewardToast';t.className='rewardToast';document.body.appendChild(t)}t.textContent=`✓ Objectif atteint · +${n} 🦷`;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(showRewardToast.t);showRewardToast.t=setTimeout(()=>t.classList.remove('show'),1800)}
const oldReward=reward;reward=function(g,date){let before=data.teeth;oldReward(g,date);if(date<=today()&&data.teeth>before)showRewardToast(data.teeth-before)}
const oldReportRow=reportRow;reportRow=function(g){let html=oldReportRow(g),m=typeMeta(g);return html.replace(`<h3>${g.name}</h3>`,`<span class="typeTag">${m.icon} ${m.label}</span><h3>${g.name}</h3>`).replace(`<div class="pace">${g.category||'Autre'}</div>`,`<div class="reportIdentity">${g.type==='habit'?'Régularité & série':g.type==='cumulative'?'Progression cumulée':g.type==='metric'?(g.deadline?'Réel vs trajectoire':'Mesure vs cible'):'Progression vers échéance'}</div>`)}
const oldSettings=$('#settingsBtn').onclick;$('#settingsBtn').onclick=()=>alert('SharkHabits V16.4 — UX overhaul\nSuivi quotidien · rapports · océan · collection de 26 requins.');
// Swipe horizontal on the Today week strip: one week backward/forward.
let swipeX=null;const weekEl=$('#week');if(weekEl){weekEl.addEventListener('touchstart',e=>{swipeX=e.changedTouches[0].clientX},{passive:true});weekEl.addEventListener('touchend',e=>{if(swipeX===null)return;let dx=e.changedTouches[0].clientX-swipeX;swipeX=null;if(Math.abs(dx)<55)return;let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()+(dx<0?7:-7));selectedDate=iso(d);render()},{passive:true})}
data.version=V164;save();render();
