/* SharkHabits V16.5 — aquarium engine */
const V165='16.5';
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function migrateAquarium(){data.placed=(data.placed||[]).map(p=>({...p,x:clamp(Number.isFinite(+p.x)?+p.x:50,10,90),y:clamp(Number.isFinite(+p.y)?+p.y:72,12,88),size:clamp(Number.isFinite(+p.size)?+p.size:18,10,32),layer:p.layer==='back'?'back':'front'}))}
function aquariumScene(el,{editing=false}={}){if(!el)return;let shark=SHARKS.find(s=>s.id===data.activeShark)||SHARKS[0];el.classList.toggle('editing',editing);el.dataset.shark=shark.id;el.innerHTML=`<div class="waterGlow"></div>${(data.placed||[]).filter(p=>p.layer==='back').map(decorHTML).join('')}<img class="mainShark" src="${shark.img}" alt="${shark.name}" draggable="false">${(data.placed||[]).filter(p=>p.layer!=='back').map(decorHTML).join('')}<div class="aquariumHUD"><span>${editing?'Glisse les décors · touche × pour retirer':shark.name}</span></div>`;el.querySelectorAll('img').forEach(img=>{img.draggable=false;img.decoding='async'});if(editing)bindDecorDrag(el)}
function decorHTML(p){let d=DECORS.find(x=>x.id===p.decor);if(!d)return'';return `<button type="button" class="placedDecor" data-remove="${p.id}" data-layer="${p.layer||'front'}" style="left:${clamp(+p.x||50,10,90)}%;top:${clamp(+p.y||70,12,88)}%;--decor-size:${clamp(+p.size||18,10,32)}%" aria-label="${d.name}"><img src="${d.img}" alt="${d.name}"></button>`}
function bindDecorDrag(el){el.querySelectorAll('.placedDecor').forEach(node=>{let moved=false;node.addEventListener('pointerdown',ev=>{moved=false;node.setPointerCapture(ev.pointerId);let move=e=>{moved=true;let r=el.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width*100,8,92),y=clamp((e.clientY-r.top)/r.height*100,8,92),p=data.placed.find(q=>q.id===node.dataset.remove);if(p){p.x=x;p.y=y;node.style.left=x+'%';node.style.top=y+'%'}};let up=()=>{node.removeEventListener('pointermove',move);save()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up,{once:true})});node.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation()}})})}
function renderAquariums(){aquariumScene($('#aquariumPreview'));if($('#aquariumDialog').open)aquariumScene($('#aquariumFull'),{editing:$('#inventory').classList.contains('visible')})}
const v165OldOcean=renderOcean;renderOcean=function(){v165OldOcean();renderAquariums()};
scene=function(el){aquariumScene(el,{editing:el===document.querySelector('#aquariumFull')&&$('#inventory')?.classList.contains('visible')})};
function openAquariumV165(edit=false){aquariumScene($('#aquariumFull'),{editing:edit});$('#inventory').classList.toggle('visible',edit);$('#editAquarium').textContent=edit?'OK':'Décorer';if(!$('#aquariumDialog').open)$('#aquariumDialog').showModal()}
$('#oceanCard').onclick=()=>openAquariumV165(false);$('#decorate').onclick=()=>openAquariumV165(true);$('#editAquarium').onclick=()=>{let edit=!$('#inventory').classList.contains('visible');openAquariumV165(edit)};
$('#aquariumFull').addEventListener('click',e=>{let b=e.target.closest('.placedDecor');if(!b||!$('#inventory').classList.contains('visible'))return;if(e.offsetX>b.clientWidth-30&&e.offsetY<30){data.placed=data.placed.filter(p=>p.id!==b.dataset.remove);save();openAquariumV165(true)}});
// Inventory remains compatible with the existing V16.4 handler; normalize new placements after every tap.
$('#inventory').addEventListener('click',()=>setTimeout(()=>{let p=(data.placed||[]).at(-1);if(p){p.x=clamp(+p.x||50,10,90);p.y=clamp(+p.y||72,12,88);p.size=clamp(+p.size||18,10,32);p.layer=p.layer||'front';save();openAquariumV165(true)}},0));
migrateAquarium();data.version=V165;save();render();
