/* SharkHabits V16.5.1 — stability layer */
const V1651='16.5.1';
function isFlexibleGoal(g){return g.scheduleMode==='timesweek'||g.scheduleMode==='period'||g.type==='deadline'||(g.type==='cumulative'&&g.repeat!=='day')||(g.type==='metric'&&g.deadline)}
function dailyState(g,dateStr=selectedDate){let amount=dailyAmount(g,dateStr),has=entries(g).some(e=>e.date===dateStr),planned=scheduledOn(g,dateStr);if(!planned)return'not-planned';if(isFlexibleGoal(g)){if(has)return'done';return dateStr>today()?'future':'optional'}if(g.type==='metric')return has?'done':dateStr<today()?'missed':'todo';let done=amount>0;return done?'done':dateStr<today()?'missed':dateStr>today()?'future':'todo'}
function trajectoryState(g,dateStr=selectedDate){let s=targetState(g,dateStr);return{s,...s,label:s.complete?'Objectif atteint':s.good?'Dans le rythme':'À surveiller'}}
function weeklyStreak(g,dateStr=selectedDate){let cursor=monday(new Date(Math.min(new Date(dateStr+'T12:00'),new Date(today()+'T12:00')))),n=0,target=Math.max(1,+g.timesPerWeek||1);for(let w=0;w<520;w++){let a=iso(cursor),b=iso(new Date(cursor.getTime()+6*DAY)),hits=new Set(entries(g).filter(e=>e.date>=a&&e.date<=b&&+e.value>0).map(e=>e.date)).size;if(hits<target)break;n++;cursor=new Date(cursor.getTime()-7*DAY)}return n}
const v1651BaseStreak=streak;streak=function(g){return g.scheduleMode==='timesweek'?weeklyStreak(g):v1651BaseStreak(g)};
function dailyStatusText(g,dateStr=selectedDate){let d=dailyState(g,dateStr);return d==='done'?'Fait ce jour':d==='missed'?'Manqué ce jour':d==='not-planned'?'Non prévu ce jour':d==='optional'?'Aucune saisie ce jour':d==='future'?'À venir':'À faire aujourd’hui'}
const v1651OldTask=task;task=function(g,kind){let html=v1651OldTask(g,kind),t=trajectoryState(g),day=dailyStatusText(g);return html.replace(/<div class="trackFoot">/,`<div class="dualStatus"><span>${day}</span><strong class="${t.good||t.complete?'good':'bad'}">${t.label}</strong></div><div class="trackFoot">`)};
renderToday=function(){renderWeek();let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,selectedDate)),groups={todo:[],done:[],missed:[],flex:[]};gs.forEach(g=>{let d=dailyState(g,selectedDate);if(d==='done')groups.done.push(g);else if(d==='missed')groups.missed.push(g);else if(d==='optional'||isFlexibleGoal(g))groups.flex.push(g);else groups.todo.push(g)});let defs=[['À faire',groups.todo,'todo'],['Suivis de période',groups.flex,'flex'],['Terminé',groups.done,'done'],['Manqué',groups.missed,'missed']];$('#todayGroups').innerHTML=defs.filter(x=>x[1].length).map(x=>`<div class="groupTitle"><h3>${x[0]}</h3><span>${x[1].length}</span></div><div class="taskGroup">${x[1].map(g=>task(g,x[2])).join('')}</div>`).join('')||`<div class="emptyState"><div class="emptyIcon">✓</div><strong>Rien de prévu</strong><p class="muted">Aucun objectif n’est planifié ce jour.</p></div>`;let strict=gs.filter(g=>!isFlexibleGoal(g)),done=strict.filter(g=>dailyState(g,selectedDate)==='done').length,avg=strict.length?done/strict.length*100:0;$('#dayScore').textContent=`${done}/${strict.length}`;$('#dayBar').style.width=avg+'%';let label=$('.summary span');if(label)label.textContent='Tâches du jour'};
subtract=function(g){let es=entries(g),period=es.filter(e=>{let[a,b]=bounds(g,selectedDate);return e.date>=a&&e.date<=b});let day=es.filter(e=>e.date===selectedDate),pool=day.length?day:period;if(!pool.length)return;let last=pool.at(-1);if(g.type==='metric'||g.type==='habit'||+last.value<=1)data.entries=data.entries.filter(e=>e.id!==last.id);else last.value=Math.max(0,+last.value-1);save();render()};
const v1651OldReportRow=reportRow;reportRow=function(g){let html=v1651OldReportRow(g),t=trajectoryState(g);return html.replace(/En bonne voie|En retard/g,t.label)};
// Future dates remain browsable, but cannot earn teeth.
reward=function(g,date){if(g.type==='metric'||date>today())return;let k=`${g.id}:${date}`;if(!data.rewardLog[k]){data.rewardLog[k]=true;data.teeth+=3;showRewardToast(3)}};
// Aquarium inventory is normalized without assuming that every inventory click created a placement.
$('#inventory').addEventListener('click',()=>requestAnimationFrame(()=>{for(const p of(data.placed||[])){p.x=clamp(+p.x||50,10,90);p.y=clamp(+p.y||72,12,88);p.size=clamp(+p.size||18,10,32);p.layer=p.layer==='back'?'back':'front'}save();renderAquariums()}));
data.version=V1651;save();render();
