/* SharkHabits V16.6 — consolidation & long-term reliability */
const V166='16.6';
function isCurrentWeek(dateStr=selectedDate){let a=monday(new Date(dateStr+'T12:00')),b=monday(new Date(today()+'T12:00'));return iso(a)===iso(b)}
weeklyStreak=function(g,dateStr=selectedDate){let cursor=monday(new Date(Math.min(new Date(dateStr+'T12:00'),new Date(today()+'T12:00')))),n=0,target=Math.max(1,+g.timesPerWeek||1);for(let w=0;w<520;w++){let a=iso(cursor),b=iso(new Date(cursor.getTime()+6*DAY)),hits=new Set(entries(g).filter(e=>e.date>=a&&e.date<=b&&+e.value>0).map(e=>e.date)).size;if(w===0&&isCurrentWeek(a)&&hits<target){cursor=new Date(cursor.getTime()-7*DAY);continue}if(hits<target)break;n++;cursor=new Date(cursor.getTime()-7*DAY)}return n};
streak=function(g){return g.scheduleMode==='timesweek'?weeklyStreak(g):v1651BaseStreak(g)};
function goalCompleteForReward(g,dateStr){if(g.type==='metric')return false;if(g.type==='habit'&&g.scheduleMode==='timesweek'){let hits=weeklyHits(g,dateStr).filter(Boolean).length;return hits>=Math.max(1,+g.timesPerWeek||1)}if(g.type==='deadline'||g.type==='cumulative')return targetState(g,dateStr).complete||isDone(g);return isDone(g)}
reward=function(g,date){if(date>today()||!goalCompleteForReward(g,date))return;let key=g.scheduleMode==='timesweek'?`${g.id}:week:${iso(monday(new Date(date+'T12:00')))}`:g.repeat==='week'?`${g.id}:week:${iso(monday(new Date(date+'T12:00')))}`:g.repeat==='month'?`${g.id}:month:${date.slice(0,7)}`:`${g.id}:${date}`;if(!data.rewardLog[key]){data.rewardLog[key]=true;data.teeth+=3;showRewardToast(3);save()}};
function freshness(g){if(g.type!=='metric')return'';let es=entries(g).filter(e=>e.date<=selectedDate);if(!es.length)return'Jamais mesuré';let last=es.at(-1),days=Math.max(0,Math.floor((new Date(selectedDate+'T12:00')-new Date(last.date+'T12:00'))/DAY));return days===0?'Mesuré aujourd’hui':`Dernière mesure · il y a ${days} jour${days>1?'s':''}`}
const v166TaskBase=task;task=function(g,kind){let html=v166TaskBase(g,kind);if(g.type==='metric'){let f=freshness(g);html=html.replace('</div><div class="trackFoot">',`<small class="freshness">${f}</small></div><div class="trackFoot">`)}return html};
// Prevent accidental period-wide subtraction: minus only changes the selected day's latest entry.
subtract=function(g){let day=entries(g).filter(e=>e.date===selectedDate);if(!day.length){showActionToast('Aucune saisie à retirer ce jour');return}let last=day.at(-1);if(g.type==='metric'||g.type==='habit'||+last.value<=1)data.entries=data.entries.filter(e=>e.id!==last.id);else last.value=Math.max(0,+last.value-1);save();render()};
function showActionToast(text){let t=$('#actionToast');if(!t){t=document.createElement('div');t.id='actionToast';t.className='rewardToast';document.body.appendChild(t)}t.textContent=text;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(showActionToast.t);showActionToast.t=setTimeout(()=>t.classList.remove('show'),1600)}
// Future trajectory is explicitly prospective.
const v166Trajectory=trajectoryState;trajectoryState=function(g,dateStr=selectedDate){let r=v166Trajectory(g,dateStr);if(dateStr>today()&&!r.complete)r.label='Prévu';return r};
// Aquarium: stop legacy inventory listeners from receiving taps; this layer owns add/remove/drag behavior.
const inv=$('#inventory');if(inv){inv.addEventListener('click',e=>{let item=e.target.closest('[data-decor]');if(!item)return;e.stopImmediatePropagation();let id=item.dataset.decor,d=DECORS.find(x=>x.id===id);if(!d||!(data.ownedDecor||[]).includes(id))return;data.placed.push({id:uid(),decor:id,x:50,y:70,size:18,layer:'front'});save();openAquariumV165(true)},true)}
// Progressive disclosure in goal editor: hide irrelevant advanced fields.
function syncGoalForm(){let f=$('#goalForm');if(!f)return;let type=f.elements.type.value,mode=f.elements.scheduleMode.value;f.querySelectorAll('[data-v166-conditional]').forEach(x=>x.hidden=true);f.querySelectorAll(`[data-v166-conditional~="${type}"],[data-v166-conditional~="${mode}"]`).forEach(x=>x.hidden=false)}
function enhanceGoalForm(){let f=$('#goalForm');if(!f||f.dataset.v166)return;f.dataset.v166='1';let labels=[...f.querySelectorAll(':scope>label')];for(const l of labels){let n=l.querySelector('[name]')?.name;if(['direction','startValue','deadline','rule'].includes(n))l.dataset.v166Conditional='metric deadline';if(n==='timesPerWeek')l.dataset.v166Conditional='timesweek'}let days=f.querySelector('.scheduleDays');if(days)days.dataset.v166Conditional='days';let hint=document.createElement('div');hint.className='formHint';hint.textContent='Commence par le type et le rythme : SharkHabits n’affiche ensuite que les réglages utiles.';f.querySelector('.dialogHead').after(hint);f.elements.type.addEventListener('change',syncGoalForm);f.elements.scheduleMode.addEventListener('change',syncGoalForm);syncGoalForm()}
enhanceGoalForm();
data.version=V166;save();render();
