/* SharkHabits V16.7 — clean consolidated runtime. Loads after app.js only. */
const V167='16.7';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function dailyAmount(g,dateStr=selectedDate){return entries(g).filter(e=>e.date===dateStr).reduce((s,e)=>s+(+e.value||0),0)}
function weekDates(dateStr=selectedDate){let s=monday(new Date(dateStr+'T12:00'));return Array.from({length:7},(_,i)=>iso(new Date(s.getTime()+i*DAY)))}
const baseExpected=expected;expected=function(g,dateStr=selectedDate){if(g.repeat==='day')return +g.target||0;if(g.type==='metric'&&!g.deadline)return +g.target||0;return baseExpected(g,dateStr)};
function targetState(g,dateStr=selectedDate){let v=current(g,dateStr),e=expected(g,dateStr),r=g.rule||'atleast',dir=metricDirection(g),good=false,complete=false;if(g.type==='metric'){if(dir==='decrease'){good=v<=e;complete=v<=g.target}else if(dir==='increase'){good=v>=e;complete=v>=g.target}else{let t=Math.max(Math.abs(g.target)*.05,.2);good=Math.abs(v-g.target)<=t;complete=good}}else if(r==='atmost'){good=v<=g.target;complete=good}else if(r==='about'){let t=Math.max(Math.abs(g.target)*.1,1);good=Math.abs(v-e)<=t;complete=good}else{good=v>=e;complete=v>=g.target}let minOK=g.minimum!==null&&g.minimum!==undefined&&g.minimum!==''&&v>=+g.minimum;return{v,e,good,complete,minOK,diff:v-e,rule:r,dir}}
strideStatus=(g,dateStr=selectedDate)=>targetState(g,dateStr);
function isFlexibleGoal(g){return g.scheduleMode==='timesweek'||g.scheduleMode==='period'||g.type==='deadline'||(g.type==='cumulative'&&g.repeat!=='day')||(g.type==='metric'&&g.deadline)}
function dailyState(g,dateStr=selectedDate){let amount=dailyAmount(g,dateStr),has=entries(g).some(e=>e.date===dateStr),planned=scheduledOn(g,dateStr);if(!planned)return'not-planned';if(isFlexibleGoal(g))return has?'done':dateStr>today()?'future':'optional';if(g.type==='metric')return has?'done':dateStr<today()?'missed':'todo';return amount>0?'done':dateStr<today()?'missed':dateStr>today()?'future':'todo'}
function trajectoryState(g,dateStr=selectedDate){let s=targetState(g,dateStr),label=s.complete?'Objectif atteint':s.good?'Dans le rythme':'À surveiller';if(dateStr>today()&&!s.complete)label='Prévu';return{...s,label}}
function weeklyHits(g,dateStr=selectedDate){let s=monday(new Date(dateStr+'T12:00'));return Array.from({length:7},(_,i)=>{let d=iso(new Date(s.getTime()+i*DAY));return entries(g).some(e=>e.date===d&&+e.value>0)})}
function weeklyStreak(g,dateStr=selectedDate){let cursor=monday(new Date(Math.min(new Date(dateStr+'T12:00'),new Date(today()+'T12:00')))),n=0,target=Math.max(1,+g.timesPerWeek||1);for(let w=0;w<520;w++){let a=iso(cursor),b=iso(new Date(cursor.getTime()+6*DAY)),hits=new Set(entries(g).filter(e=>e.date>=a&&e.date<=b&&+e.value>0).map(e=>e.date)).size;let current=iso(cursor)===iso(monday(new Date(today()+'T12:00')));if(w===0&&current&&hits<target){cursor=new Date(cursor.getTime()-7*DAY);continue}if(hits<target)break;n++;cursor=new Date(cursor.getTime()-7*DAY)}return n}
function streak(g){if(g.scheduleMode==='timesweek')return weeklyStreak(g);let set=new Set(entries(g).filter(e=>e.value>0).map(e=>e.date)),n=0,d=new Date(Math.min(new Date(selectedDate+'T12:00'),new Date(today()+'T12:00')));while(set.has(iso(d))){n++;d=new Date(d.getTime()-DAY)}return n}
function metricDeltaText(g,dateStr=selectedDate){let s=targetState(g,dateStr),d=Math.abs(s.v-s.e),u=g.unit||'';if(d<.00001)return'Exactement sur la trajectoire';if(s.dir==='decrease')return s.v<s.e?`${fmt(d)} ${u} sous la trajectoire`:`${fmt(d)} ${u} au-dessus de la trajectoire`;return s.v>s.e?`${fmt(d)} ${u} au-dessus de la trajectoire`:`${fmt(d)} ${u} sous la trajectoire`}
function freshness(g){if(g.type!=='metric')return'';let es=entries(g).filter(e=>e.date<=selectedDate);if(!es.length)return'Jamais mesuré';let last=es.at(-1),days=Math.max(0,Math.floor((new Date(selectedDate+'T12:00')-new Date(last.date+'T12:00'))/DAY));return days===0?'Mesuré aujourd’hui':`Dernière mesure · il y a ${days} jour${days>1?'s':''}`}
function dayState(dateStr){let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,dateStr));if(!gs.length)return'empty';let ok=gs.filter(g=>g.type==='habit'?dailyAmount(g,dateStr)>0:(targetState(g,dateStr).good||targetState(g,dateStr).complete||targetState(g,dateStr).minOK)).length;return ok===gs.length?'done':ok>0?'partial':dateStr<today()?'missed':'pending'}
renderWeek=function(){let s=monday(new Date(selectedDate+'T12:00')),e=new Date(s.getTime()+6*DAY),wr=$('#weekRange'),jd=$('#jumpDate');if(wr)wr.textContent=`${s.toLocaleDateString('fr-FR',{day:'numeric',month:'long'})} – ${e.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}`;if(jd)jd.value=selectedDate;$('#week').innerHTML=Array.from({length:7},(_,i)=>new Date(s.getTime()+i*DAY)).map(d=>{let id=iso(d),state=dayState(id);return `<button class="day ${id===selectedDate?'active':''} ${state}" data-date="${id}"><span>${d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','').toUpperCase()}</span><b>${d.getDate()}</b><i></i></button>`}).join('')};
function identity(g,s,p){let v=s.v;if(g.type==='habit'){let hits=weeklyHits(g),target=g.scheduleMode==='timesweek'?Math.max(1,+g.timesPerWeek||1):null;return `<div class="habitDots">${hits.map(x=>`<i class="${x?'hit':''}">${x?'✓':'·'}</i>`).join('')}</div><small>${target?`${hits.filter(Boolean).length} / ${target} cette semaine`:`Série · ${streak(g)} jour${streak(g)>1?'s':''}`}</small>`}if(g.type==='cumulative')return `<div class="identityBar"><i style="width:${p}%"></i></div><small>${fmt(v)} / ${fmt(g.target)} ${g.unit||''} · ${periodLabel(g)}</small>`;if(g.type==='metric')return `<div class="trajectoryToday"><span>${g.deadline?'Trajectoire aujourd’hui':'Cible'} <b>${fmt(g.deadline?s.e:g.target)} ${g.unit||''}</b></span><strong class="${s.good?'good':'bad'}">${metricDeltaText(g)}</strong><small class="freshness">${freshness(g)}</small></div>`;let left=g.deadline?Math.max(0,Math.ceil((new Date(g.deadline+'T12:00')-new Date(selectedDate+'T12:00'))/DAY)):null;return `<div class="identityBar"><i style="width:${p}%"></i></div><small>${Math.round(p)} %${left!==null?` · ${left} jour${left>1?'s':''} restant${left>1?'s':''}`:''}</small>`}
function dailyStatusText(g,dateStr=selectedDate){let d=dailyState(g,dateStr);return d==='done'?'Fait ce jour':d==='missed'?'Manqué ce jour':d==='not-planned'?'Non prévu ce jour':d==='optional'?'Aucune saisie ce jour':d==='future'?'À venir':'À faire aujourd’hui'}
task=function(g,kind){let s=trajectoryState(g),p=pct(g),m=typeMeta(g),v=s.v;return `<article class="trackingCard ${m.cls} ${kind==='missed'?'missed':''}" data-detail="${g.id}"><div class="trackHead"><div><span class="typeTag">${m.icon} ${m.label}</span><h4>${g.name}</h4></div><strong class="trackValue">${fmt(v)}${g.unit?` ${g.unit}`:''}</strong></div><div class="identity">${identity(g,s,p)}</div><div class="dualStatus"><span>${dailyStatusText(g)}</span><strong class="${s.good||s.complete?'good':'bad'}">${s.label}</strong></div><div class="trackFoot"><span class="${s.good?'good':'bad'}">${s.label}</span><div class="stepper"><button data-minus="${g.id}" aria-label="Soustraire">−</button><button data-add="${g.id}" aria-label="Ajouter">＋</button></div></div></article>`};
renderToday=function(){renderWeek();let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,selectedDate)),groups={todo:[],done:[],missed:[],flex:[]};gs.forEach(g=>{let d=dailyState(g);if(d==='done')groups.done.push(g);else if(d==='missed')groups.missed.push(g);else if(d==='optional'||isFlexibleGoal(g))groups.flex.push(g);else groups.todo.push(g)});let defs=[['À faire',groups.todo,'todo'],['Suivis de période',groups.flex,'flex'],['Terminé',groups.done,'done'],['Manqué',groups.missed,'missed']];$('#todayGroups').innerHTML=defs.filter(x=>x[1].length).map(x=>`<div class="groupTitle"><h3>${x[0]}</h3><span>${x[1].length}</span></div><div class="taskGroup">${x[1].map(g=>task(g,x[2])).join('')}</div>`).join('')||`<div class="emptyState"><div class="emptyIcon">✓</div><strong>Rien de prévu</strong><p class="muted">Aucun objectif n’est planifié ce jour.</p></div>`;let strict=gs.filter(g=>!isFlexibleGoal(g)),done=strict.filter(g=>dailyState(g)==='done').length,avg=strict.length?done/strict.length*100:0;$('#dayScore').textContent=`${done}/${strict.length}`;$('#dayBar').style.width=avg+'%';let label=$('.summary span');if(label)label.textContent='Tâches du jour'};
function showRewardToast(n=3){let t=$('#rewardToast');if(!t){t=document.createElement('div');t.id='rewardToast';t.className='rewardToast';document.body.appendChild(t)}t.textContent=`✓ Objectif atteint · +${n} 🦷`;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(showRewardToast.t);showRewardToast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function goalCompleteForReward(g,dateStr){if(g.type==='metric')return false;if(g.type==='habit'&&g.scheduleMode==='timesweek')return weeklyHits(g,dateStr).filter(Boolean).length>=Math.max(1,+g.timesPerWeek||1);return targetState(g,dateStr).complete||isDone(g,dateStr)}
reward=function(g,date){if(date>today()||!goalCompleteForReward(g,date))return;let key=g.scheduleMode==='timesweek'||g.repeat==='week'?`${g.id}:week:${iso(monday(new Date(date+'T12:00')))}`:g.repeat==='month'?`${g.id}:month:${date.slice(0,7)}`:`${g.id}:${date}`;if(!data.rewardLog[key]){data.rewardLog[key]=true;data.teeth+=3;showRewardToast(3)}};
function showActionToast(text){let t=$('#actionToast');if(!t){t=document.createElement('div');t.id='actionToast';t.className='rewardToast';document.body.appendChild(t)}t.textContent=text;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(showActionToast.t);showActionToast.t=setTimeout(()=>t.classList.remove('show'),1600)}
subtract=function(g){let day=entries(g).filter(e=>e.date===selectedDate);if(!day.length){showActionToast('Aucune saisie à retirer ce jour');return}let last=day.at(-1);if(g.type==='metric'||g.type==='habit'||+last.value<=1)data.entries=data.entries.filter(e=>e.id!==last.id);else last.value=Math.max(0,+last.value-1);save();render()};
function decorHTML(p){let d=DECORS.find(x=>x.id===p.decor);if(!d)return'';return `<button type="button" class="placedDecor" data-remove="${p.id}" data-layer="${p.layer||'front'}" style="left:${clamp(+p.x||50,10,90)}%;top:${clamp(+p.y||70,12,88)}%;--decor-size:${clamp(+p.size||18,10,32)}%" aria-label="${d.name}"><img src="${d.img}" alt="${d.name}"></button>`}
function bindDecorDrag(el){el.querySelectorAll('.placedDecor').forEach(node=>{let moved=false;node.addEventListener('pointerdown',ev=>{moved=false;node.setPointerCapture(ev.pointerId);let move=e=>{moved=true;let r=el.getBoundingClientRect(),p=data.placed.find(q=>q.id===node.dataset.remove);if(p){p.x=clamp((e.clientX-r.left)/r.width*100,8,92);p.y=clamp((e.clientY-r.top)/r.height*100,8,92);node.style.left=p.x+'%';node.style.top=p.y+'%'}};node.addEventListener('pointermove',move);node.addEventListener('pointerup',()=>{node.removeEventListener('pointermove',move);save()},{once:true})});node.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation()}})})}
function aquariumScene(el,{editing=false}={}){if(!el)return;let shark=SHARKS.find(s=>s.id===data.activeShark)||SHARKS[0];el.classList.toggle('editing',editing);el.dataset.shark=shark.id;el.innerHTML=`<div class="waterGlow"></div>${(data.placed||[]).filter(p=>p.layer==='back').map(decorHTML).join('')}<img class="mainShark" src="${shark.img}" alt="${shark.name}" draggable="false">${(data.placed||[]).filter(p=>p.layer!=='back').map(decorHTML).join('')}<div class="aquariumHUD"><span>${editing?'Glisse les décors · touche × pour retirer':shark.name}</span></div>`;if(editing)bindDecorDrag(el)}
function migrateAquarium(){data.placed=(data.placed||[]).map(p=>({...p,x:clamp(Number.isFinite(+p.x)?+p.x:50,10,90),y:clamp(Number.isFinite(+p.y)?+p.y:72,12,88),size:clamp(Number.isFinite(+p.size)?+p.size:18,10,32),layer:p.layer==='back'?'back':'front'}))}
function openAquarium(edit=false){editMode=edit;aquariumScene($('#aquariumFull'),{editing:edit});renderInv();$('#inventory').classList.toggle('visible',edit);$('#editAquarium').textContent=edit?'OK':'Décorer';if(!$('#aquariumDialog').open)$('#aquariumDialog').showModal()}
scene=function(el){aquariumScene(el,{editing:el===$('#aquariumFull')&&editMode})};
renderOcean=function(){$('#teeth').textContent=data.teeth;aquariumScene($('#aquariumPreview'))};
$('#oceanCard').onclick=()=>openAquarium(false);$('#decorate').onclick=()=>openAquarium(true);$('#editAquarium').onclick=()=>openAquarium(!editMode);
$('#aquariumFull').addEventListener('click',e=>{let b=e.target.closest('.placedDecor');if(!b||!editMode)return;let r=b.getBoundingClientRect();if(e.clientX>r.right-32&&e.clientY<r.top+32){let p=data.placed.find(x=>x.id===b.dataset.remove);if(p){data.inventory[p.decor]=(data.inventory[p.decor]||0)+1;data.placed=data.placed.filter(x=>x.id!==p.id);save();openAquarium(true)}}});
$('#inventory').addEventListener('click',e=>{let item=e.target.closest('[data-place]');if(!item)return;e.stopImmediatePropagation();let id=item.dataset.place;if((data.inventory[id]||0)<1)return;data.inventory[id]--;data.placed.push({id:uid(),decor:id,x:50,y:70,size:18,layer:'front'});save();openAquarium(true)},true);
const prev=$('#prevWeek'),next=$('#nextWeek'),tb=$('#todayBtn'),jump=$('#jumpDate');if(prev)prev.onclick=()=>{let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()-7);selectedDate=iso(d);render()};if(next)next.onclick=()=>{let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()+7);selectedDate=iso(d);render()};if(tb)tb.onclick=()=>{selectedDate=today();render()};if(jump)jump.onchange=e=>{if(e.target.value){selectedDate=e.target.value;render()}};
function syncGoalForm(){let f=$('#goalForm');if(!f)return;let type=f.elements.type.value,mode=f.elements.scheduleMode.value;f.querySelectorAll('[data-v167-conditional]').forEach(x=>x.hidden=true);f.querySelectorAll(`[data-v167-conditional~="${type}"],[data-v167-conditional~="${mode}"]`).forEach(x=>x.hidden=false)}
(function enhanceGoalForm(){let f=$('#goalForm');if(!f)return;[...f.querySelectorAll(':scope>label')].forEach(l=>{let n=l.querySelector('[name]')?.name;if(['direction','startValue','deadline','rule'].includes(n))l.dataset.v167Conditional='metric deadline';if(n==='timesPerWeek')l.dataset.v167Conditional='timesweek'});let days=f.querySelector('.scheduleDays');if(days)days.dataset.v167Conditional='days';f.elements.type.addEventListener('change',syncGoalForm);f.elements.scheduleMode.addEventListener('change',syncGoalForm);syncGoalForm()})();
// One authoritative entry submitter; rewards are evaluated after the new value exists.
$('#entryForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.currentTarget)),g=data.goals.find(x=>x.id===o.goal),v=+o.value;if(!g||!Number.isFinite(v)||v<0)return;if(g.type==='metric')data.entries=data.entries.filter(x=>!(x.goal===g.id&&x.date===o.date));data.entries.push({id:uid(),goal:g.id,value:v,date:o.date,note:o.entryNote||''});reward(g,o.date);save();$('#entryDialog').close();render()};
$('#settingsBtn').onclick=()=>alert('SharkHabits V18.14\n26 espèces · données enregistrées localement.');
migrateAquarium();data.version=V167;save();render();
