/* SharkHabits V16.9 — metric baseline + dated trajectory milestones */
const V169='16.9';
function metricMilestones(g){if(g.type!=='metric'||g.startValue==null)return[];let start=new Date((g.created||today())+'T12:00'),end=g.deadline?new Date(g.deadline+'T12:00'):null;if(!end||end<=start)return[{date:iso(start),value:+g.startValue,label:'Départ'}];let days=Math.max(1,Math.round((end-start)/DAY)),step=days<=70?7:days<=400?30:90,out=[];for(let d=new Date(start);d<end;d=new Date(d.getTime()+step*DAY)){let ds=iso(d);out.push({date:ds,value:expected(g,ds),label:d.getTime()===start.getTime()?'Départ':'Jalon'})}out.push({date:iso(end),value:+g.target,label:'Objectif'});return out}
function ensureMetricBaseline(g){if(!g||g.type!=='metric'||g.startValue==null||g.startValue==='')return;let date=g.created||today(),exists=data.entries.some(e=>e.goal===g.id&&e.date===date&&e.baseline);if(!exists)data.entries.push({id:uid(),goal:g.id,value:+g.startValue,date,baseline:true,note:'Valeur initiale'})}
function migrateMetricBaselines(){data.goals.filter(g=>g.type==='metric'&&g.startValue!=null&&g.startValue!=='').forEach(ensureMetricBaseline)}
function validateMetricStart(){let f=$('#goalForm');if(!f)return true;if(f.elements.type.value!=='metric')return true;let s=f.elements.startValue;if(!s||s.value===''){s?.setCustomValidity('Renseigne une valeur initiale pour tracer la trajectoire.');s?.reportValidity();return false}s.setCustomValidity('');return true}
$('#goalForm')?.addEventListener('input',e=>{if(e.target.name==='startValue')e.target.setCustomValidity('')});
$('#goalForm')?.addEventListener('submit',e=>{if(!validateMetricStart()){e.preventDefault();e.stopImmediatePropagation();return}let id=e.currentTarget.elements.id.value;setTimeout(()=>{let g=id?data.goals.find(x=>x.id===id):data.goals.at(-1);if(g?.type==='metric'){if(!g.created)g.created=today();ensureMetricBaseline(g);save();render()}},0)},true);
function trajectoryMilestoneSVG(g,W,H,pad,min,max){let ms=metricMilestones(g),x=d=>pad+(new Date(d+'T12:00')-new Date((g.created||today())+'T12:00'))/Math.max(DAY,new Date((g.deadline||d)+'T12:00')-new Date((g.created||today())+'T12:00'))*(W-2*pad),y=v=>H-pad-(v-min)/Math.max(.0001,max-min)*(H-2*pad);return ms.map((m,i)=>{let X=x(m.date),Y=y(m.value),date=new Date(m.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'});let show=i===0||i===ms.length-1||ms.length<=8||i%Math.ceil(ms.length/7)===0;return `<g class="milestone"><circle cx="${X}" cy="${Y}" r="4"><title>${date} · cible ${fmt(m.value)} ${g.unit||''}</title></circle>${show?`<text x="${X}" y="${H-5}" text-anchor="middle">${date}</text>`:''}</g>`}).join('')}
const v169Detail=detail;detail=function(g){v169Detail(g);if(g.type!=='metric'||g.startValue==null)return;let body=$('#detailBody'),old=body?.querySelector('.metricMilestoneSummary');if(old)old.remove();let s=targetState(g),box=document.createElement('div');box.className='metricMilestoneSummary';box.innerHTML=`<div><span>Départ</span><strong>${fmt(g.startValue)} ${g.unit||''}</strong></div><div><span>Cible théorique aujourd’hui</span><strong>${fmt(s.e)} ${g.unit||''}</strong></div><div><span>Objectif</span><strong>${fmt(g.target)} ${g.unit||''}${g.deadline?` · ${new Date(g.deadline+'T12:00').toLocaleDateString('fr-FR')}`:''}</strong></div>`;body?.prepend(box);let svg=body?.querySelector('svg');if(svg&&g.deadline){let vals=[+g.startValue,+g.target,...entries(g).map(e=>+e.value)],min=Math.min(...vals),max=Math.max(...vals);if(max===min){max+=1;min-=1}let vb=(svg.getAttribute('viewBox')||'0 0 600 220').split(/\s+/).map(Number),W=vb[2]||600,H=vb[3]||220,pad=28;svg.insertAdjacentHTML('beforeend',trajectoryMilestoneSVG(g,W,H,pad,min,max))}}
migrateMetricBaselines();data.version=V169;save();render();
