/* SharkHabits V17.1.3 — authoritative Strides Reports runtime */
const V171='17.1.3';let v171Mode='progress';
const v171Active=g=>!!g&&!g.archived&&!g.archivedAt&&!g.completedAt;
const v171Num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function v171Status(g){try{return strideStatus(g)}catch(e){return{good:false,v:v171Num(current(g)),e:v171Num(g.target)}}}
function v171Pct(g){try{return Math.max(0,Math.min(100,v171Num(pct(g))))}catch(e){return 0}}
function v171Goals(){let gs=(data.goals||[]).filter(v171Active);if(v171Mode==='repeat')return gs.filter(g=>g.type==='habit'||['day','week','month'].includes(g.repeat));if(v171Mode==='deadline')return gs.filter(g=>!!g.deadline);return gs}
function v171Line(g){let s;try{s=stat(g)}catch(e){s={v:v171Num(current(g)),e:v171Num(g.target)}}let st=v171Status(g),p=v171Pct(g),target=v171Num(g.target),marker=g.type==='metric'?Math.max(5,Math.min(95,p)):Math.max(5,Math.min(95,target?100*v171Num(s.e)/target:50)),due=g.deadline?`${fmt(target)} ${g.unit||''} au ${new Date(g.deadline+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}`:`${fmt(target)} ${g.unit||''} ${periodLabel(g)}`;return `<button class="v171GoalLine" data-detail="${g.id}"><div class="v171GoalMain"><span>${esc(g.name||'Objectif')}</span><strong>${fmt(v171Num(s.v))}${g.unit?` ${esc(g.unit)}`:''}</strong></div><div class="v171Rail"><i class="${st.good?'ok':'late'}" style="width:${Math.max(1,p)}%"></i><b style="left:${marker}%"></b></div><div class="v171GoalMeta"><span class="${st.good?'okText':'lateText'}">${st.good?'Dans le rythme':'À surveiller'}</span><span>${due}</span></div></button>`}
function v171Rows(gs){return gs.map(g=>{try{return v171Line(g)}catch(e){console.error('Report row failed',g,e);return `<button class="v171GoalLine" data-detail="${g.id}"><div class="v171GoalMain"><span>${esc(g.name||'Objectif')}</span><strong>›</strong></div><div class="v171GoalMeta"><span>Voir la progression</span><span></span></div></button>`}}).join('')}
function v171RenderReports(){let summary=$('#reportSummary'),list=$('#reportList');if(!summary||!list)return;let gs=v171Goals(),avg=gs.length?gs.reduce((n,g)=>n+v171Pct(g),0)/gs.length:0,good=gs.filter(g=>v171Status(g).good).length;summary.innerHTML=`<div class="v171Title"><span>♙ Mes objectifs</span></div><div class="v171Modes"><button data-v171mode="progress" class="${v171Mode==='progress'?'active':''}">☷ Progression</button><button data-v171mode="repeat" class="${v171Mode==='repeat'?'active':''}">↻ Répétition</button><button data-v171mode="deadline" class="${v171Mode==='deadline'?'active':''}">⚑ Date de l’objectif</button></div><div class="v171Summary"><div><strong>Progression moyenne : ${Math.round(avg)} %</strong><span>${good}/${gs.length}<small> en bonne voie</small></span></div><div class="v171SummaryRail"><i style="width:${avg}%"></i></div></div>`;list.innerHTML=gs.length?v171Rows(gs):'<div class="emptyState"><strong>Aucun objectif actif</strong><p>Crée un objectif ou une habitude pour commencer.</p></div>';list.dataset.v171Count=String(gs.length)}
renderReports=v171RenderReports;
function v171Ensure(){if(!$('#reports')?.classList.contains('active'))return;let list=$('#reportList'),wanted=v171Goals().length,shown=list?list.querySelectorAll(':scope > [data-detail]').length:0;if(!list||shown!==wanted||list.dataset.v171Count!==String(wanted))v171RenderReports()}
document.addEventListener('click',e=>{let mode=e.target.closest('[data-v171mode]');if(mode){v171Mode=mode.dataset.v171mode;v171RenderReports();return}if(e.target.closest('[data-page="reports"]')){queueMicrotask(v171RenderReports);setTimeout(v171Ensure,0);setTimeout(v171Ensure,80)}},true);
let repairQueued=false,host=$('#reportList');if(host)new MutationObserver(()=>{if(repairQueued)return;repairQueued=true;queueMicrotask(()=>{repairQueued=false;v171Ensure()})}).observe(host,{childList:true});
setInterval(v171Ensure,400);
data.version=V171;save();render();queueMicrotask(()=>{renderReports=v171RenderReports;v171Ensure()});
