/* SharkHabits V17.1.3 — authoritative Strides reports renderer */
const V171='17.1.3';
let v171Mode='progress';
function v171Range(){let d=new Date(selectedDate+'T12:00'),a,b;if(reportPeriod==='week'){let day=(d.getDay()+6)%7;a=new Date(d);a.setDate(d.getDate()-day);b=new Date(a);b.setDate(a.getDate()+6)}else if(reportPeriod==='month'){a=new Date(d.getFullYear(),d.getMonth(),1,12);b=new Date(d.getFullYear(),d.getMonth()+1,0,12)}else if(reportPeriod==='year'){a=new Date(d.getFullYear(),0,1,12);b=new Date(d.getFullYear(),11,31,12)}else return null;return{start:iso(a),end:iso(b)}}
function v171Active(g){return !!g&&!g.archived&&!g.archivedAt&&!g.completedAt}
function v171GoalTouchesPeriod(g){let r=v171Range();if(!r||v171Mode==='progress')return true;let own=data.entries.filter(e=>e.goal===g.id).map(e=>e.date).filter(Boolean).sort(),start=g.created||own[0]||today(),end=g.deadline||'9999-12-31';return start<=r.end&&end>=r.start}
function v171TypeMatch(g){if(v171Mode==='repeat')return g.type==='habit'||['day','week','month'].includes(g.repeat);if(v171Mode==='deadline')return !!g.deadline;return true}
function v171SafeNum(v,fallback=0){v=Number(v);return Number.isFinite(v)?v:fallback}
function v171SafeStatus(g){try{return strideStatus(g)}catch(_){return{good:false,v:v171SafeNum(current(g)),e:v171SafeNum(g.target)}}}
function v171SafePct(g){try{return Math.max(0,Math.min(100,v171SafeNum(pct(g))))}catch(_){return 0}}
function v171GoalLine(g){let s;try{s=stat(g)}catch(_){s={v:v171SafeNum(current(g)),e:v171SafeNum(g.target)}}let st=v171SafeStatus(g),p=v171SafePct(g),target=v171SafeNum(g.target),marker=g.type==='metric'?50:Math.max(5,Math.min(95,target?100*v171SafeNum(s.e)/target:50));let sub;if(g.deadline)sub=`${fmt(target)} ${g.unit||''} au ${typeof v17Date==='function'?v17Date(g.deadline):g.deadline}`;else if(g.type==='metric')sub=`cible ${fmt(target)} ${g.unit||''}`;else sub=`${fmt(target)} ${g.unit||''} ${periodLabel(g)}`;return `<button class="v171GoalLine" data-detail="${g.id}"><div class="v171GoalMain"><span>${esc(g.name||'Objectif')}</span><strong>${fmt(v171SafeNum(s.v))}${g.unit?` ${esc(g.unit)}`:''}</strong></div><div class="v171Rail"><i class="${st.good?'ok':'late'}" style="width:${Math.max(1,p)}%"></i><b style="left:${marker}%"></b></div><div class="v171GoalMeta"><span class="${st.good?'okText':'lateText'}">${st.good?'Dans le rythme':'À surveiller'}</span><span>${sub}</span></div></button>`}
function v171VisibleGoals(){return (data.goals||[]).filter(v171Active).filter(v171GoalTouchesPeriod).filter(v171TypeMatch)}
function v171PaintRows(goals){let host=$('#reportList');if(!host)return;let html=goals.map(g=>{try{return v171GoalLine(g)}catch(err){console.error('V17.1.3 report row',g?.id,err);return `<button class="v171GoalLine" data-detail="${g.id}"><div class="v171GoalMain"><span>${esc(g.name||'Objectif')}</span><strong>›</strong></div><div class="v171GoalMeta"><span>Voir la progression</span><span></span></div></button>`}}).join('');host.innerHTML=html||'<div class="emptyState"><strong>Aucun objectif actif</strong><p>Les objectifs créés apparaîtront ici.</p></div>'}
function v171RenderReports(){let active=v171VisibleGoals(),vals=active.map(v171SafePct),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,good=active.filter(g=>v171SafeStatus(g).good).length;let summary=$('#reportSummary');if(summary)summary.innerHTML=`<div class="v171Title"><span>♙ Mes objectifs</span></div><div class="v171Modes"><button data-v171mode="progress" class="${v171Mode==='progress'?'active':''}">☷ Progression</button><button data-v171mode="repeat" class="${v171Mode==='repeat'?'active':''}">↻ Répétition</button><button data-v171mode="deadline" class="${v171Mode==='deadline'?'active':''}">⚑ Date de l’objectif</button></div><div class="v171Summary"><div><strong>Progression moyenne : ${Math.round(avg)} %</strong><span>${good}/${active.length}<small> en bonne voie</small></span></div><div class="v171SummaryRail"><i style="width:${Math.max(0,Math.min(100,avg))}%"></i></div></div>`;v171PaintRows(active)}
renderReports=v171RenderReports;
document.addEventListener('click',e=>{let b=e.target.closest('[data-v171mode]');if(!b)return;v171Mode=b.dataset.v171mode;v171RenderReports()},true);
/* Legacy layers in V16.10/V17 can still repaint #reportList. If that happens, restore the authoritative rows without recursively calling render(). */
let v171Repairing=false;const v171Host=$('#reportList');if(v171Host){new MutationObserver(()=>{if(v171Repairing||!$('#reports')?.classList.contains('active'))return;let goals=v171VisibleGoals(),shown=v171Host.querySelectorAll('[data-detail]').length;if(goals.length&&shown<goals.length){v171Repairing=true;v171PaintRows(goals);queueMicrotask(()=>v171Repairing=false)}}).observe(v171Host,{childList:true,subtree:false})}
data.version=V171;save();v171RenderReports();render();setTimeout(()=>{renderReports=v171RenderReports;if($('#reports')?.classList.contains('active'))v171RenderReports()},0);
