/* SharkHabits V17.1.1 — Strides reports + reliable goal visibility */
const V171='17.1.1';
let v171Mode='progress';
function v171Range(){let d=new Date(selectedDate+'T12:00'),a,b;if(reportPeriod==='week'){let day=(d.getDay()+6)%7;a=new Date(d);a.setDate(d.getDate()-day);b=new Date(a);b.setDate(a.getDate()+6)}else if(reportPeriod==='month'){a=new Date(d.getFullYear(),d.getMonth(),1,12);b=new Date(d.getFullYear(),d.getMonth()+1,0,12)}else if(reportPeriod==='year'){a=new Date(d.getFullYear(),0,1,12);b=new Date(d.getFullYear(),11,31,12)}else return null;return{start:iso(a),end:iso(b)}}
function v171GoalTouchesPeriod(g){let r=v171Range();if(!r)return true;let ownEntries=data.entries.filter(e=>e.goal===g.id).map(e=>e.date).sort(),start=g.created||ownEntries[0]||today(),end=g.deadline||'9999-12-31';return start<=r.end&&end>=r.start}
function v171TypeMatch(g){if(v171Mode==='repeat')return g.type==='habit'||g.repeat==='day'||g.repeat==='week'||g.repeat==='month';if(v171Mode==='deadline')return !!g.deadline;return true}
function v171GoalLine(g){let s=stat(g),st=strideStatus(g),p=Math.max(0,Math.min(100,pct(g))),marker=g.type==='metric'?Math.max(5,Math.min(95,50)):Math.max(5,Math.min(95,(s.e/(+g.target||1))*100)),sub=g.type==='metric'?(g.deadline?`${fmt(g.target)} ${g.unit||''} au ${v17Date(g.deadline)}`:`cible ${fmt(g.target)} ${g.unit||''}`):(g.deadline?`${fmt(g.target)} ${g.unit||''} au ${v17Date(g.deadline)}`:`${fmt(g.target)} ${g.unit||''} ${periodLabel(g)}`);return `<button class="v171GoalLine" data-detail="${g.id}"><div class="v171GoalMain"><span>${esc(g.name)}</span><strong>${fmt(s.v)}${g.unit?` ${g.unit}`:''}</strong></div><div class="v171Rail"><i class="${st.good?'ok':'late'}" style="width:${Math.max(1,p)}%"></i><b style="left:${marker}%"></b></div><div class="v171GoalMeta"><span class="${st.good?'okText':'lateText'}">${st.good?'Dans le rythme':'À surveiller'}</span><span>${sub}</span></div></button>`}
function v171ReportFilter(g){let tab=(reportTab==='progress'||reportTab==='all'||!reportTab)?'all':reportTab;if(tab==='good')return strideStatus(g).good;if(tab==='late')return !strideStatus(g).good;return true}
renderReports=function(){let active=data.goals.filter(v17Active).filter(v171GoalTouchesPeriod).filter(v171TypeMatch),visible=active.filter(v171ReportFilter),avg=active.length?active.reduce((n,g)=>n+pct(g),0)/active.length:0,good=active.filter(g=>strideStatus(g).good).length;$('#reportSummary').innerHTML=`<div class="v171Title"><h2>Rapports</h2><span>♙ Mes objectifs</span></div><div class="v171Modes"><button data-v171mode="progress" class="${v171Mode==='progress'?'active':''}">☷ Progression</button><button data-v171mode="repeat" class="${v171Mode==='repeat'?'active':''}">↻ Répétition</button><button data-v171mode="deadline" class="${v171Mode==='deadline'?'active':''}">⚑ Date de l’objectif</button></div><div class="v171Summary"><div><strong>Progression moyenne : ${Math.round(avg)} %</strong><span>${good}/${active.length}<small> en bonne voie</small></span></div><div class="v171SummaryRail"><i style="width:${Math.max(0,Math.min(100,avg))}%"></i></div></div>`;$('#reportList').innerHTML=visible.map(v171GoalLine).join('')||'<div class="emptyState"><strong>Aucun objectif sur cette période</strong><p>Les objectifs actifs pendant la période apparaissent ici, même si leur échéance est plus tard.</p></div>';let inactive=data.goals.filter(g=>g.archivedAt||g.completedAt);if(reportPeriod==='all'&&inactive.length)$('#reportList').insertAdjacentHTML('beforeend',`<section class="inactiveGoals"><div class="sectionHead"><div><span class="eyebrow">HISTORIQUE</span><h2>Terminés & archivés</h2></div><span>${inactive.length}</span></div><div class="inactiveGoalList">${inactive.map(g=>`<button class="inactiveGoal" data-detail="${g.id}"><span><strong>${esc(g.name)}</strong><small>${g.completedAt?'Terminé':'Archivé'} · ${g.completedAt||g.archivedAt}</small></span><span>›</span></button>`).join('')}</div></section>`)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-v171mode]');if(!b)return;v171Mode=b.dataset.v171mode;renderReports()},true);
data.version=V171;save();render();
