/* SharkHabits V18.2 — clear, contextual, single-screen editor */
(()=>{const dlg=document.getElementById('goalDialog'),form=document.getElementById('goalForm');if(!dlg||!form)return;const f=n=>form.elements[n],set=(n,v)=>{if(f(n))f(n).value=v},getType=()=>f('type')?.value||'habit';const TYPES={habit:['✓','Habitude'],cumulative:['＋','Quantité'],metric:['↗','Cible'],deadline:['⚑','Projet']};
function infer(){const t=getType();if(t==='metric'){const a=parseFloat(f('startValue')?.value),b=parseFloat(f('target')?.value);set('direction',Number.isFinite(a)&&Number.isFinite(b)?(b<a?'decrease':b>a?'increase':'maintain'):'auto');set('repeat','once');set('rule','about');set('scheduleMode','period')}else if(t==='habit'){set('direction','increase');set('rule','atleast')}else if(t==='cumulative'){set('direction','increase');set('rule','atleast');set('scheduleMode','period')}else{set('direction','increase');set('rule','atleast');set('repeat','once');set('scheduleMode','period')}}
function defaults(t){if(t==='habit'){set('target',1);set('unit','fois');set('repeat','day');set('scheduleMode','everyday')}if(t==='cumulative'){set('target',10);set('unit','');set('repeat','week')}if(t==='metric'){set('unit','kg');set('repeat','once')}if(t==='deadline'){set('target',1);set('unit','étape');set('repeat','once')}infer()}
function visible(el,on){if(el)el.hidden=!on}
function apply(){infer();const t=getType(),q=s=>form.querySelector(s);form.querySelectorAll('.v182Type').forEach(b=>b.classList.toggle('active',b.dataset.type===t));visible(q('[data-v="target"]'),true);visible(q('[data-v="unit"]'),true);visible(q('[data-v="repeat"]'),t==='habit'||t==='cumulative');visible(q('[data-v="start"]'),t==='metric');visible(q('[data-v="deadline"]'),t==='metric'||t==='deadline');visible(q('[data-v="planning"]'),t==='habit');const mode=f('scheduleMode')?.value;visible(q('[data-v="days"]'),t==='habit'&&(mode==='days'||mode==='everyday'));visible(q('[data-v="times"]'),t==='habit'&&mode==='timesweek');visible(q('[data-v="category"]'),true);visible(q('[data-v="note"]'),true);const title=document.getElementById('goalDialogTitle');if(title&&!f('id')?.value)title.textContent=t==='habit'?'Ajouter une habitude':t==='metric'?'Ajouter une cible':t==='deadline'?'Ajouter un projet':'Ajouter une quantité'}
function build(){if(form.dataset.v182)return;form.dataset.v182='1';const direct=[...form.children],find=txt=>direct.find(el=>el.tagName==='LABEL'&&el.textContent.trim().startsWith(txt));const typeLabel=find('Type'),name=find('Nom'),two=form.querySelector(':scope>.two'),pairs=two?[...two.querySelectorAll(':scope>label')]:[];typeLabel.hidden=true;name.dataset.step='1';name.dataset.caption='Nom';pairs[0]?.setAttribute('data-v','target');pairs[1]?.setAttribute('data-v','unit');[['Répétition','repeat'],['Valeur initiale','start'],['Échéance','deadline'],['Planning','planning'],['Fois par semaine','times'],['Note','note'],['Catégorie','category']].forEach(([a,b])=>find(a)?.setAttribute('data-v',b));form.querySelector('.scheduleDays')?.setAttribute('data-v','days');find('Direction').hidden=true;find('Règle').hidden=true;
const choose=document.createElement('section');choose.className='v182Choose';choose.innerHTML='<div class="v182Label"><i>1</i><span>Que voulez-vous créer ?</span></div><div class="v182Types">'+Object.entries(TYPES).map(([k,a])=>`<button type="button" class="v182Type" data-type="${k}"><b>${a[0]}</b><span>${a[1]}</span></button>`).join('')+'</div>';typeLabel.before(choose);name.insertAdjacentHTML('afterbegin','<span class="v182Label"><i>2</i><span>Nom</span></span>');
const config=document.createElement('div');config.className='v182ConfigTitle';config.innerHTML='<i>3</i><span>Configuration</span>';two.before(config);const cat=find('Catégorie');cat?.insertAdjacentHTML('afterbegin','<span class="v182Label"><i>4</i><span>Catégorie</span></span>');const save=form.querySelector('.dialogHead button[type="submit"]');save.textContent='Ajouter';save.classList.add('v182Save');
choose.addEventListener('click',e=>{const b=e.target.closest('[data-type]');if(!b)return;set('type',b.dataset.type);defaults(b.dataset.type);apply()});form.addEventListener('input',apply);form.addEventListener('change',apply);apply()}
const old=dlg.showModal.bind(dlg);dlg.showModal=()=>{build();old();requestAnimationFrame(apply)};build();})();