/* SharkHabits V18.1 — contextual Strides-inspired editor */
(()=>{const dlg=document.getElementById('goalDialog'),form=document.getElementById('goalForm');if(!dlg||!form)return;
const info={habit:['✓','Habitude','Action à répéter'],cumulative:['▥','Quantité','Nombre à cumuler'],deadline:['≡','Projet','Actions avant une date'],metric:['⌁','Cible','Valeur à atteindre']};
const f=n=>form.elements[n],set=(n,v)=>{if(f(n))f(n).value=v},type=()=>f('type')?.value||'habit';
function defaults(t){if(t==='habit'){set('target',1);set('unit','fois');set('repeat','day');set('direction','increase');set('rule','atleast');set('scheduleMode','everyday')}else if(t==='cumulative'){set('target',10);set('unit','');set('repeat','week');set('direction','increase');set('rule','atleast');set('scheduleMode','period')}else if(t==='deadline'){set('target',1);set('unit','étape');set('repeat','once');set('direction','increase');set('rule','atleast');set('scheduleMode','period')}else{set('repeat','once');set('rule','about');set('scheduleMode','period')}}
function infer(){const t=type();if(t==='metric'){const a=Number(f('startValue')?.value),b=Number(f('target')?.value);set('direction',Number.isFinite(a)&&Number.isFinite(b)?(b<a?'decrease':b>a?'increase':'maintain'):'auto')}if(t==='habit')set('rule','atleast');if(t==='deadline'||t==='cumulative')set('direction','increase')}
function preview(){infer();const t=type(),name=f('name')?.value||'Mon suivi',target=f('target')?.value||'—',unit=f('unit')?.value||'',start=f('startValue')?.value,d=f('deadline')?.value;let s=t==='metric'&&start?`${start}${unit?' '+unit:''} → ${target}${unit?' '+unit:''}`:`${target}${unit?' '+unit:''}`;if(t==='habit')s+=` · ${f('repeat')?.selectedOptions?.[0]?.textContent||''}`;if(t==='cumulative')s+=` · ${f('repeat')?.selectedOptions?.[0]?.textContent||''}`;if(d)s+=` · ${new Date(d+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}`;form.querySelector('.v18Preview').innerHTML=`<small>APERÇU</small><strong>${esc(name)}</strong><span>${esc(s)}</span>`}
function show(el,on){if(el)el.classList.toggle('v181Visible',!!on)}
function apply(t){set('type',t);form.dataset.v18type=t;form.querySelectorAll('.v18Type').forEach(b=>b.classList.toggle('active',b.dataset.type===t));const q=s=>form.querySelector(s);show(q('[data-f="target"]'),true);show(q('[data-f="unit"]'),true);show(q('[data-f="repeat"]'),t==='habit'||t==='cumulative');show(q('[data-f="start"]'),t==='metric');show(q('[data-f="deadline"]'),t==='metric'||t==='deadline');show(q('[data-f="schedule"]'),t==='habit');show(q('[data-f="days"]'),t==='habit'&&f('scheduleMode')?.value==='days');show(q('[data-f="times"]'),t==='habit'&&f('scheduleMode')?.value==='timesweek');show(q('[data-f="note"]'),true);show(q('[data-f="category"]'),true);preview()}
function enhance(){if(form.dataset.v181ready)return;form.dataset.v181ready='1';const labels=[...form.querySelectorAll(':scope>label')],find=x=>labels.find(l=>l.textContent.trim().startsWith(x)),name=find('Nom'),typeLabel=find('Type'),two=form.querySelector(':scope>.two');name?.classList.add('v18Name');typeLabel?.classList.add('v18LegacyType');if(two){[...two.querySelectorAll('label')][0]?.setAttribute('data-f','target');[...two.querySelectorAll('label')][1]?.setAttribute('data-f','unit');two.classList.add('v181Fields')}
[['Répétition','repeat'],['Valeur initiale','start'],['Échéance','deadline'],['Planning','schedule'],['Fois par semaine','times'],['Note','note'],['Catégorie','category']].forEach(([x,k])=>find(x)?.setAttribute('data-f',k));form.querySelector('.scheduleDays')?.setAttribute('data-f','days');['Direction','Règle'].forEach(x=>find(x)?.classList.add('v181Internal'));
const chooser=document.createElement('div');chooser.className='v18Chooser';chooser.innerHTML=`<p>Comment voulez-vous suivre ceci ?</p><div class="v18TypeGrid">${Object.entries(info).map(([k,a])=>`<button type="button" class="v18Type" data-type="${k}"><b>${a[0]}</b><strong>${a[1]}</strong><span>${a[2]}</span></button>`).join('')}</div>`;typeLabel.before(chooser);const pv=document.createElement('div');pv.className='v18Preview';form.appendChild(pv);
chooser.addEventListener('click',e=>{const b=e.target.closest('[data-type]');if(!b)return;defaults(b.dataset.type);apply(b.dataset.type)});form.addEventListener('input',()=>{apply(type())});form.addEventListener('change',()=>{apply(type())});apply(type())}
const old=dlg.showModal.bind(dlg);dlg.showModal=()=>{enhance();old();requestAnimationFrame(()=>apply(type()))};enhance();
})();