/* SharkHabits V18 — Strides-inspired goal wizard, preserving legacy data schema */
(()=>{const dlg=document.getElementById('goalDialog'),form=document.getElementById('goalForm');if(!dlg||!form)return;
const typeInfo={habit:['✓','Habitude','Actions à répéter'],cumulative:['▥','Quantité','Nombre à cumuler'],deadline:['≡','Projet','Actions avant une date'],metric:['⌁','Cible','Valeur à atteindre']};
function field(n){return form.elements[n]}
function val(n,v){if(field(n))field(n).value=v}
function selectedType(){return field('type')?.value||'habit'}
function defaults(t){if(t==='habit'){val('target',1);val('unit','fois');val('repeat','day');val('direction','increase');val('rule','atleast');val('scheduleMode','everyday')}if(t==='cumulative'){val('target',10);val('unit','');val('repeat','week');val('direction','increase');val('rule','atleast');val('scheduleMode','period')}if(t==='deadline'){val('target',1);val('unit','étape');val('repeat','once');val('direction','increase');val('rule','atleast');val('scheduleMode','period')}if(t==='metric'){val('unit','kg');val('repeat','once');val('direction','auto');val('rule','about');val('scheduleMode','period')}}
function preview(){const t=selectedType(),name=field('name')?.value||'Mon suivi',target=field('target')?.value||'—',unit=field('unit')?.value||'',start=field('startValue')?.value,deadline=field('deadline')?.value,repeat=field('repeat')?.selectedOptions?.[0]?.textContent||'';let line=`${target}${unit?' '+unit:''} · ${repeat}`;if(t==='metric'&&start)line=`${start}${unit?' '+unit:''} → ${target}${unit?' '+unit:''}`;if(deadline)line+=` · avant le ${new Date(deadline+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}`;const p=form.querySelector('.v18Preview');if(p)p.innerHTML=`<small>APERÇU</small><strong>${esc(name)}</strong><span>${esc(line)}</span>`}
function applyType(t){val('type',t);form.querySelectorAll('.v18Type').forEach(b=>b.classList.toggle('active',b.dataset.type===t));form.dataset.v18type=t;const metric=t==='metric',deadline=t==='deadline';form.querySelector('[data-v18-start]')?.classList.toggle('show',metric);form.querySelector('[data-v18-deadline]')?.classList.toggle('requiredType',metric||deadline);form.querySelector('[data-v18-direction]')?.classList.toggle('show',metric);preview()}
function enhance(){if(form.dataset.v18ready)return;form.dataset.v18ready='1';const name=field('name'),type=field('type');type.closest('label').classList.add('v18LegacyType');name.closest('label').classList.add('v18Name');const chooser=document.createElement('div');chooser.className='v18Chooser';chooser.innerHTML=`<p>Comment voulez-vous suivre ceci ?</p><div class="v18TypeGrid">${Object.entries(typeInfo).map(([k,a])=>`<button type="button" class="v18Type" data-type="${k}"><b>${a[0]}</b><strong>${a[1]}</strong><span>${a[2]}</span></button>`).join('')}</div>`;type.closest('label').before(chooser);
const labels=[...form.querySelectorAll(':scope>label')];const find=t=>labels.find(l=>l.textContent.trim().startsWith(t));find('Valeur initiale')?.setAttribute('data-v18-start','');find('Échéance')?.setAttribute('data-v18-deadline','');find('Direction')?.setAttribute('data-v18-direction','');const adv=document.createElement('details');adv.className='v18Advanced';adv.innerHTML='<summary>Options avancées <span>⌄</span></summary><div class="v18AdvancedBody"></div>';const body=adv.querySelector('div');['Direction','Règle','Planning','Fois par semaine','Note','Catégorie'].forEach(x=>{const l=find(x);if(l)body.appendChild(l)});const days=form.querySelector('.scheduleDays');if(days)body.appendChild(days);form.appendChild(adv);const pv=document.createElement('div');pv.className='v18Preview';form.appendChild(pv);
chooser.addEventListener('click',e=>{const b=e.target.closest('[data-type]');if(!b)return;defaults(b.dataset.type);applyType(b.dataset.type)});form.addEventListener('input',preview);form.addEventListener('change',preview);applyType(selectedType());preview()}
const oldShow=dlg.showModal.bind(dlg);dlg.showModal=()=>{enhance();oldShow();setTimeout(()=>{applyType(selectedType());preview()},0)};enhance();
})();