/* SharkHabits V18.7 — Living Ocean */
(()=>{
const EXTRA=[
 {id:'island',name:'Île tropicale',cost:900,emoji:'🏝️',zone:'surface'},
 {id:'sailboat',name:'Voilier',cost:700,emoji:'⛵',zone:'surface'},
 {id:'submarine',name:'Sous-marin',cost:1200,emoji:'🚤',zone:'mid'},
 {id:'dome-house',name:'Maison dôme',cost:950,emoji:'🫧',zone:'floor'},
 {id:'pineapple-house',name:'Maison ananas',cost:1100,emoji:'🍍',zone:'floor'},
 {id:'rock-house',name:'Maison roche',cost:1000,emoji:'🗿',zone:'floor'},
 {id:'lighthouse',name:'Phare sur îlot',cost:1350,emoji:'🗼',zone:'surface'},
 {id:'research-base',name:'Base sous-marine',cost:1600,emoji:'🔬',zone:'floor'}
];
window.SHARKHABITS_LIVING_DECORS=EXTRA;
function ensure(){data.inventory||={};data.placed||=[];data.activeSharks||=[data.activeShark||'grey'];if(!Array.isArray(data.activeSharks))data.activeSharks=[data.activeShark||'grey'];data.activeSharks=data.activeSharks.filter(id=>data.ownedSharks.includes(id)).slice(0,5);if(!data.activeSharks.length)data.activeSharks=[data.activeShark||'grey'];}
function score(){let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,today()));return gs.length?Math.round(gs.reduce((s,g)=>s+pct(g,today()),0)/gs.length):0}
function extraNode(p){let d=EXTRA.find(x=>x.id===p.decor);if(!d)return'';return `<button class="livingDecor zone-${d.zone}" data-remove-extra="${p.id}" style="left:${p.x??45}%;top:${p.y??65}%"><span>${d.emoji}</span></button>`}
function sharks(){ensure();return data.activeSharks.map((id,i)=>{let s=SHARKS.find(x=>x.id===id);if(!s)return'';return `<img class="livingShark shark-${i%5}" src="${s.img}" alt="${s.name}">`}).join('')}
function scene(){ensure();let old=data.placed.filter(p=>!EXTRA.some(x=>x.id===p.decor)).map(p=>{let d=DECORS.find(x=>x.id===p.decor);return d?`<span class="livingOldDecor" style="left:${p.x||20}%;top:${p.y||70}%"><img src="${d.img}" alt=""></span>`:''}).join('');let extra=data.placed.map(extraNode).join('');return `<div class="waterSurface"></div><div class="sunRays"></div><div class="oceanParticles"></div><div class="distantFish">‹  ‹‹　‹　　‹‹</div>${sharks()}<div class="seaFloor"></div>${old}${extra}<div class="livingBubbles"><i></i><i></i><i></i><i></i><i></i><i></i></div>`}
function renderLiving(){let o=document.querySelector('#ocean');if(!o)return;let p=score();o.innerHTML=`<div class="livingHud"><div><span>MON OCÉAN</span><strong>${p}% aujourd’hui</strong></div><b>🦷 ${data.teeth}</b></div><div id="livingScene" class="livingScene vitality-${Math.floor(p/25)}">${scene()}</div><div class="livingControls"><button id="livingDecorate">🪸 Décorer</button><button id="livingSharks">🦈 Requins</button></div><div id="livingDrawer" class="livingDrawer"></div>`}
function decorDrawer(){ensure();let drawer=document.querySelector('#livingDrawer');drawer.classList.add('open');drawer.innerHTML=`<div class="drawerHead"><strong>Décorer l’océan</strong><button data-close-drawer>✕</button></div><div class="livingShop">${EXTRA.map(d=>{let owned=(data.inventory[d.id]||0)>data.placed.filter(p=>p.decor===d.id).length;return `<button data-living-decor="${d.id}"><span>${d.emoji}</span><b>${d.name}</b><small>${owned?'Placer':`🦷 ${d.cost}`}</small></button>`}).join('')}</div><small class="drawerHint">Les décors de surface restent près de la surface. Les maisons et bases se placent sur le fond.</small>`}
function sharkDrawer(){ensure();let drawer=document.querySelector('#livingDrawer');drawer.classList.add('open');drawer.innerHTML=`<div class="drawerHead"><strong>Requins dans l’océan</strong><button data-close-drawer>✕</button></div><div class="livingShop">${data.ownedSharks.map(id=>{let s=SHARKS.find(x=>x.id===id),on=data.activeSharks.includes(id);return s?`<button data-living-shark="${id}" class="${on?'selected':''}"><img src="${s.img}"><b>${s.name}</b><small>${on?'✓ Dans l’océan':'Ajouter'}</small></button>`:''}).join('')}</div><small class="drawerHint">Jusqu’à 5 requins peuvent nager ensemble.</small>`}
function buyOrPlace(id){ensure();let d=EXTRA.find(x=>x.id===id);if(!d)return;let used=data.placed.filter(p=>p.decor===id).length,owned=data.inventory[id]||0;if(owned<=used){if(data.teeth<d.cost){alert('Pas assez de dents.');return}data.teeth-=d.cost;data.inventory[id]=(data.inventory[id]||0)+1}let y=d.zone==='surface'?8:d.zone==='mid'?43:72;data.placed.push({id:uid(),decor:id,x:12+Math.random()*65,y});save();renderLiving();decorDrawer()}
function toggleShark(id){ensure();let a=data.activeSharks,i=a.indexOf(id);if(i>=0){if(a.length===1)return;a.splice(i,1)}else{if(a.length>=5)a.shift();a.push(id)}data.activeShark=a[0];save();renderLiving();sharkDrawer()}
document.addEventListener('click',e=>{if(e.target.closest('[data-page="ocean"]'))setTimeout(renderLiving,0);if(e.target.closest('#livingDecorate'))decorDrawer();if(e.target.closest('#livingSharks'))sharkDrawer();let d=e.target.closest('[data-living-decor]');if(d)buyOrPlace(d.dataset.livingDecor);let s=e.target.closest('[data-living-shark]');if(s)toggleShark(s.dataset.livingShark);if(e.target.closest('[data-close-drawer]'))document.querySelector('#livingDrawer')?.classList.remove('open');let r=e.target.closest('[data-remove-extra]');if(r&&document.querySelector('#livingDrawer')?.classList.contains('open')){data.placed=data.placed.filter(p=>p.id!==r.dataset.removeExtra);save();renderLiving();decorDrawer()}});
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();if(document.querySelector('#ocean.active'))renderLiving()};ensure();save();
})();