/* SharkHabits V18.7.1 — Living Ocean unified store */
(()=>{
const EXTRA=[
 {id:'island',name:'Île tropicale',cost:900,img:'decor-island.svg',zone:'surface'},
 {id:'sailboat',name:'Voilier',cost:700,img:'decor-sailboat.svg',zone:'surface'},
 {id:'submarine',name:'Sous-marin',cost:1200,img:'decor-submarine.svg',zone:'mid'},
 {id:'dome-house',name:'Maison dôme',cost:950,emoji:'◉',zone:'floor'},
 {id:'pineapple-house',name:'Maison ananas',cost:1100,emoji:'🍍',zone:'floor'},
 {id:'rock-house',name:'Maison roche',cost:1000,emoji:'🗿',zone:'floor'},
 {id:'lighthouse',name:'Phare sur îlot',cost:1350,emoji:'♜',zone:'surface'},
 {id:'research-base',name:'Base sous-marine',cost:1600,emoji:'⌂',zone:'floor'}
];
const BAD_FAUNA=new Set(['clownfish','bluefish','school','turtle','babyturtle']);
const BASE_DECORS=DECORS.filter(d=>!BAD_FAUNA.has(d.id));
let decorFilter='all';
window.SHARKHABITS_LIVING_DECORS=EXTRA;
function ensure(){data.inventory||={};data.placed||=[];data.activeSharks||=[data.activeShark||'grey'];if(!Array.isArray(data.activeSharks))data.activeSharks=[data.activeShark||'grey'];data.activeSharks=data.activeSharks.filter(id=>data.ownedSharks.includes(id)).slice(0,5);if(!data.activeSharks.length)data.activeSharks=[data.activeShark||'grey'];data.placed=data.placed.filter(p=>!BAD_FAUNA.has(p.decor));}
function score(){let gs=data.goals.filter(g=>!g.archived&&scheduledOn(g,today()));return gs.length?Math.round(gs.reduce((s,g)=>s+pct(g,today()),0)/gs.length):0}
function decorDef(id){return EXTRA.find(x=>x.id===id)||BASE_DECORS.find(x=>x.id===id)}
function decorVisual(d){return d.img?`<img src="${d.img}" alt="${d.name}">`:`<span>${d.emoji||'🪸'}</span>`}
function extraNode(p){let d=EXTRA.find(x=>x.id===p.decor);if(!d)return'';return `<button class="livingDecor zone-${d.zone}" data-remove-extra="${p.id}" style="left:${p.x??45}%;top:${p.y??65}%">${decorVisual(d)}</button>`}
function sharks(){ensure();return data.activeSharks.map((id,i)=>{let s=SHARKS.find(x=>x.id===id);return s?`<img class="livingShark shark-${i%5}" src="${s.img}" alt="${s.name}">`:''}).join('')}
function scene(){ensure();let old=data.placed.filter(p=>!EXTRA.some(x=>x.id===p.decor)).map(p=>{let d=BASE_DECORS.find(x=>x.id===p.decor);return d?`<span class="livingOldDecor" style="left:${p.x||20}%;top:${p.y||70}%"><img src="${d.img}" alt="${d.name}"></span>`:''}).join('');let extra=data.placed.map(extraNode).join('');return `<div class="waterSurface"></div><div class="sunRays"></div><div class="oceanParticles"></div><div class="distantFish">‹  ‹‹　‹　　‹‹</div>${sharks()}<div class="seaFloor"></div>${old}${extra}<div class="livingBubbles"><i></i><i></i><i></i><i></i><i></i><i></i></div>`}
function renderLiving(){let o=document.querySelector('#ocean');if(!o)return;let p=score();o.innerHTML=`<div class="livingHud"><div><span>MON OCÉAN</span><strong>${p}% aujourd’hui</strong></div><b>🦷 ${data.teeth}</b></div><div id="livingScene" class="livingScene vitality-${Math.floor(p/25)}">${scene()}</div><div class="livingControls"><button id="livingDecorate">🪸 Décorer & acheter</button><button id="livingSharks">🦈 Requins</button></div><div id="livingDrawer" class="livingDrawer"></div>`}
function isDecorOwned(d){return (data.inventory[d.id]||0)>0}
function decorDrawer(){ensure();let all=[...BASE_DECORS,...EXTRA],list=all.filter(d=>decorFilter==='owned'?isDecorOwned(d):decorFilter==='buy'?!isDecorOwned(d):true),drawer=document.querySelector('#livingDrawer');drawer.classList.add('open');drawer.innerHTML=`<div class="drawerHead"><strong>Décorer l’océan</strong><button data-close-drawer>✕</button></div><div class="oceanFilters"><button data-decor-filter="all" class="${decorFilter==='all'?'active':''}">Tout</button><button data-decor-filter="owned" class="${decorFilter==='owned'?'active':''}">Possédés</button><button data-decor-filter="buy" class="${decorFilter==='buy'?'active':''}">À acheter</button></div><div class="livingShop">${list.map(d=>{let available=(data.inventory[d.id]||0)>data.placed.filter(p=>p.decor===d.id).length;return `<button data-living-decor="${d.id}" class="${isDecorOwned(d)?'owned':''}">${decorVisual(d)}<b>${d.name}</b><small>${available?'Placer':`🦷 ${d.cost} · Acheter`}</small></button>`}).join('')}</div><small class="drawerHint">Achète et place directement ici. Les anciennes tortues et poissons au style différent ont été retirés du catalogue.</small>`}
function sharkDrawer(){ensure();let drawer=document.querySelector('#livingDrawer');drawer.classList.add('open');drawer.innerHTML=`<div class="drawerHead"><strong>Requins</strong><button data-close-drawer>✕</button></div><div class="livingShop sharkShop">${SHARKS.map(s=>{let owned=data.ownedSharks.includes(s.id),on=data.activeSharks.includes(s.id);return `<button data-living-shark="${s.id}" class="${on?'selected':''}"><img src="${s.img}" alt="${s.name}"><b>${s.name}</b><small>${on?'✓ Dans l’océan':owned?'Ajouter':`🦷 ${s.cost} · Acheter`}</small></button>`}).join('')}</div><small class="drawerHint">Tous les achats sont désormais faits depuis ton Océan. Jusqu’à 5 requins peuvent nager ensemble.</small>`}
function buyOrPlace(id){ensure();let d=decorDef(id);if(!d)return;let used=data.placed.filter(p=>p.decor===id).length,owned=data.inventory[id]||0;if(owned<=used){if(data.teeth<d.cost){alert('Pas assez de dents.');return}data.teeth-=d.cost;data.inventory[id]=(data.inventory[id]||0)+1}let zone=d.zone||(id==='wreck'||id==='statue'||id==='chest'?'floor':'floor'),y=zone==='surface'?8:zone==='mid'?43:72;data.placed.push({id:uid(),decor:id,x:12+Math.random()*65,y});save();renderLiving();decorDrawer()}
function toggleShark(id){ensure();let s=SHARKS.find(x=>x.id===id);if(!s)return;if(!data.ownedSharks.includes(id)){if(data.teeth<s.cost){alert('Pas assez de dents.');return}data.teeth-=s.cost;data.ownedSharks.push(id)}let a=data.activeSharks,i=a.indexOf(id);if(i>=0){if(a.length===1){save();renderLiving();sharkDrawer();return}a.splice(i,1)}else{if(a.length>=5)a.shift();a.push(id)}data.activeShark=a[0];save();renderLiving();sharkDrawer()}
document.addEventListener('click',e=>{if(e.target.closest('[data-page="ocean"]'))setTimeout(renderLiving,0);if(e.target.closest('#livingDecorate'))decorDrawer();if(e.target.closest('#livingSharks'))sharkDrawer();let f=e.target.closest('[data-decor-filter]');if(f){decorFilter=f.dataset.decorFilter;decorDrawer()}let d=e.target.closest('[data-living-decor]');if(d)buyOrPlace(d.dataset.livingDecor);let s=e.target.closest('[data-living-shark]');if(s)toggleShark(s.dataset.livingShark);if(e.target.closest('[data-close-drawer]'))document.querySelector('#livingDrawer')?.classList.remove('open');let r=e.target.closest('[data-remove-extra]');if(r&&document.querySelector('#livingDrawer')?.classList.contains('open')){data.placed=data.placed.filter(p=>p.id!==r.dataset.removeExtra);save();renderLiving();decorDrawer()}});
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();if(document.querySelector('#ocean.active'))renderLiving()};ensure();save();
})();